"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class ConvexHull2D:
    """
    sc.fiji.snt.analysis.ConvexHull2D
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.244794
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def boundarySize(self) -> float: ...
    
    def compute(self) -> None: ...
    
    def getPolygon(self) -> Any: ...
    
    # Multiple overloads for intersection
    def intersection(self, arg0: Any) -> Any: ...
    # def intersection(self, arg0: Any) -> Any: ...
    
    def intersectionBox(self, arg0: Any) -> Any: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def size(self) -> float: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ConvexHull3D:
    """
    sc.fiji.snt.analysis.ConvexHull3D
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.247307
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def boundarySize(self) -> float: ...
    
    def compute(self) -> None: ...
    
    def getMesh(self) -> Any: ...
    
    # Multiple overloads for intersection
    def intersection(self, arg0: Any) -> Any: ...
    # def intersection(self, arg0: Any) -> Any: ...
    
    def intersectionBox(self, arg0: Any) -> Any: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def size(self) -> float: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TreeStatistics:
    """
    sc.fiji.snt.analysis.TreeStatistics
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.825100
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def fromCollection(self, arg0: List[Any], arg1: str) -> Any: ...
    
    def getAllMetrics(self) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedLength
    def getAnnotatedLength(self, arg0: int, arg1: str, arg2: bool) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotatedLengthHistogram
    def getAnnotatedLengthHistogram(self) -> Any: ...
    # def getAnnotatedLengthHistogram(self, arg0: int, arg1: str) -> Any: ...
    # def getAnnotatedLengthHistogram(self, arg0: int) -> Any: ...
    
    def getAnnotatedLengthsByHemisphere(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotations
    def getAnnotations(self, arg0: int) -> Set[Any]: ...
    # def getAnnotations(self) -> Set[Any]: ...
    
    def getAvgBranchLength(self) -> float: ...
    
    def getAvgContraction(self) -> float: ...
    
    def getAvgFractalDimension(self) -> float: ...
    
    def getAvgFragmentation(self) -> float: ...
    
    def getAvgPartitionAsymmetry(self) -> float: ...
    
    def getAvgRemoteBifAngle(self) -> float: ...
    
    # Multiple overloads for getBranchPoints
    def getBranchPoints(self, arg0: Any, arg1: bool) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any) -> Set[Any]: ...
    # def getBranchPoints(self) -> Set[Any]: ...
    
    def getBranches(self) -> List[Any]: ...
    
    # Multiple overloads for getCableLength
    def getCableLength(self, arg0: Any, arg1: bool) -> float: ...
    # def getCableLength(self) -> float: ...
    # def getCableLength(self, arg0: Any) -> float: ...
    
    # Multiple overloads for getCableLengthNorm
    def getCableLengthNorm(self, arg0: Any, arg1: bool) -> float: ...
    # def getCableLengthNorm(self, arg0: Any) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getConvexAnalyzer(self) -> Any: ...
    
    def getConvexHullMetric(self, arg0: str) -> float: ...
    
    def getDepth(self) -> float: ...
    
    def getDescriptiveStats(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: int) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any]) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> Any: ...
    
    def getFractalDimension(self) -> List[Any]: ...
    
    def getHeight(self) -> float: ...
    
    def getHighestPathOrder(self) -> int: ...
    
    def getHistogram(self, arg0: str) -> Any: ...
    
    def getInnerBranches(self) -> List[Any]: ...
    
    def getInnerLength(self) -> float: ...
    
    def getMetric(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getMetrics
    def getMetrics(self) -> List[Any]: ...
    # def getMetrics(self, arg0: str) -> List[Any]: ...
    
    def getNBranchPoints(self, arg0: Any) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MultiTreeStatistics:
    """
    sc.fiji.snt.analysis.MultiTreeStatistics
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.350244
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def fromCollection(self, arg0: List[Any], arg1: str) -> Any: ...
    
    def getAllMetrics(self) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedLength
    def getAnnotatedLength(self, arg0: int, arg1: str, arg2: bool) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotatedLengthHistogram
    def getAnnotatedLengthHistogram(self) -> Any: ...
    # def getAnnotatedLengthHistogram(self, arg0: int, arg1: str) -> Any: ...
    # def getAnnotatedLengthHistogram(self, arg0: int) -> Any: ...
    
    def getAnnotatedLengthsByHemisphere(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotations
    def getAnnotations(self) -> Set[Any]: ...
    # def getAnnotations(self, arg0: int) -> Set[Any]: ...
    
    def getAvgBranchLength(self) -> float: ...
    
    def getAvgContraction(self) -> float: ...
    
    def getAvgFractalDimension(self) -> float: ...
    
    def getAvgFragmentation(self) -> float: ...
    
    def getAvgPartitionAsymmetry(self) -> float: ...
    
    def getAvgRemoteBifAngle(self) -> float: ...
    
    # Multiple overloads for getBranchPoints
    def getBranchPoints(self) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any, arg1: bool) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any) -> Set[Any]: ...
    
    def getBranches(self) -> List[Any]: ...
    
    # Multiple overloads for getCableLength
    def getCableLength(self, arg0: Any) -> float: ...
    # def getCableLength(self, arg0: Any, arg1: bool) -> float: ...
    # def getCableLength(self) -> float: ...
    
    # Multiple overloads for getCableLengthNorm
    def getCableLengthNorm(self, arg0: Any, arg1: bool) -> float: ...
    # def getCableLengthNorm(self, arg0: Any) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getConvexAnalyzer(self) -> Any: ...
    
    def getConvexHullMetric(self, arg0: str) -> float: ...
    
    def getDepth(self) -> float: ...
    
    def getDescriptiveStats(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any]) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> Any: ...
    # def getFlowPlot(self, arg0: str, arg1: int) -> Any: ...
    
    def getFractalDimension(self) -> List[Any]: ...
    
    def getGroup(self) -> List[Any]: ...
    
    def getHeight(self) -> float: ...
    
    def getHighestPathOrder(self) -> int: ...
    
    def getHistogram(self, arg0: str) -> Any: ...
    
    def getInnerBranches(self) -> List[Any]: ...
    
    def getInnerLength(self) -> float: ...
    
    def getMetric(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getMetrics
    def getMetrics(self) -> List[Any]: ...
    # def getMetrics(self, arg0: str) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTChart:
    """
    sc.fiji.snt.analysis.SNTChart
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.653352
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    def actionPerformed(self, arg0: Any) -> None: ...
    
    # Multiple overloads for add
    def add(self, arg0: str, arg1: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: int) -> Any: ...
    # def add(self, arg0: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: Any) -> None: ...
    # def add(self, arg0: Any, arg1: Any, arg2: int) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    
    def addAncestorListener(self, arg0: Any) -> None: ...
    
    def addChartMouseListener(self, arg0: Any) -> None: ...
    
    def addColorBarLegend(self, arg0: str, arg1: Any, arg2: float, arg3: float, arg4: int) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addContainerListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    def addOverlay(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addPolygon
    def addPolygon(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...
    # def addPolygon(self, arg0: Any, arg1: str, arg2: str) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: Any) -> None: ...
    
    def addVetoableChangeListener(self, arg0: Any) -> None: ...
    
    # Multiple overloads for annotate
    def annotate(self, arg0: str, arg1: str, arg2: str) -> None: ...
    # def annotate(self, arg0: str) -> None: ...
    
    # Multiple overloads for annotateCategory
    def annotateCategory(self, arg0: str, arg1: str) -> None: ...
    # def annotateCategory(self, arg0: str, arg1: str, arg2: str) -> None: ...
    
    # Multiple overloads for annotatePoint
    def annotatePoint(self, arg0: Any, arg1: str, arg2: str) -> None: ...
    # def annotatePoint(self, arg0: float, arg1: float, arg2: str) -> None: ...
    # def annotatePoint(self, arg0: float, arg1: float, arg2: str, arg3: str) -> None: ...
    
    # Multiple overloads for annotateXline
    def annotateXline(self, arg0: float, arg1: str, arg2: str) -> None: ...
    # def annotateXline(self, arg0: float, arg1: str) -> None: ...
    
    # Multiple overloads for annotateYline
    def annotateYline(self, arg0: float, arg1: str) -> None: ...
    # def annotateYline(self, arg0: float, arg1: str, arg2: str) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    def applyStyle(self, arg0: Any) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    def chartChanged(self, arg0: Any) -> None: ...
    
    def chartProgress(self, arg0: Any) -> None: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    def closeAll(self) -> None: ...
    
    # Multiple overloads for combine
    def combine(self, arg0: List[Any], arg1: int, arg2: int, arg3: bool) -> Any: ...
    # def combine(self, arg0: List[Any], arg1: str, arg2: int, arg3: int, arg4: bool) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTTable:
    """
    SNTTable - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...


# Imported functions
def growth(*args: Any, **kwargs: Any) -> Any: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Callable: ...
class Dict: ...
class List: ...