"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class ConvexHull2D:
    """
    sc.fiji.snt.analysis.ConvexHull2D
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.191397
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def boundarySize(self) -> float: ...
    
    def compute(self) -> None: ...
    
    def getPolygon(self) -> Any: ...
    
    # Multiple overloads for intersection
    def intersection(self, arg0: Any) -> Any: ...
    # def intersection(self, arg0: Any) -> ConvexHull2D: ...
    
    def intersectionBox(self, arg0: Any) -> BoundingBox: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def size(self) -> float: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ConvexHull3D:
    """
    sc.fiji.snt.analysis.ConvexHull3D
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.194288
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def boundarySize(self) -> float: ...
    
    def compute(self) -> None: ...
    
    def getMesh(self) -> Any: ...
    
    # Multiple overloads for intersection
    def intersection(self, arg0: Any) -> ConvexHull3D: ...
    # def intersection(self, arg0: Any) -> Any: ...
    
    def intersectionBox(self, arg0: Any) -> BoundingBox: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def size(self) -> float: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ConvexHullAnalyzer:
    """
    sc.fiji.snt.analysis.ConvexHullAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.199176
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dump(self, arg0: SNTTable) -> None: ...
    
    def get(self, arg0: str) -> float: ...
    
    def getAnalysis(self) -> Dict[str, Any]: ...
    
    def getBoundarySize(self) -> float: ...
    
    def getBoxivity(self) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getCentroid(self) -> PointInImage: ...
    
    def getCompactness(self) -> float: ...
    
    def getContext(self) -> Any: ...
    
    def getEccentricity(self) -> float: ...
    
    def getElongation(self) -> float: ...
    
    def getHull(self) -> Any: ...
    
    def getRoundness(self) -> float: ...
    
    def getSize(self) -> float: ...
    
    def getTree(self) -> Tree: ...
    
    def getUnit(self, arg0: str) -> str: ...
    
    def isCanceled(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def run(self) -> None: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setLabel(self, arg0: str) -> None: ...
    
    def supportedMetrics(self) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class GroupedTreeStatistics:
    """
    sc.fiji.snt.analysis.GroupedTreeStatistics
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.229009
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for addGroup
    def addGroup(self, arg0: List[Any], arg1: str, arg2: Any) -> None: ...
    # def addGroup(self, arg0: List[Any], arg1: str) -> None: ...
    
    def anovaPValue(self, arg0: str) -> float: ...
    
    # Multiple overloads for getBoxPlot
    def getBoxPlot(self, arg0: str, arg1: List[Any]) -> SNTChart: ...
    # def getBoxPlot(self, arg0: str, arg1: List[Any], arg2: float, arg3: bool) -> SNTChart: ...
    # def getBoxPlot(self, arg0: str) -> SNTChart: ...
    # def getBoxPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> SNTChart: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> SNTChart: ...
    
    def getGroupStats(self, arg0: str) -> MultiTreeStatistics: ...
    
    def getGroups(self) -> List[Any]: ...
    
    def getHistogram(self, arg0: str) -> SNTChart: ...
    
    def getN(self, arg0: str) -> int: ...
    
    def getPolarHistogram(self, arg0: str) -> SNTChart: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setMinNBins(self, arg0: int) -> None: ...
    
    def tTest(self, arg0: str, arg1: str, arg2: str) -> float: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MultiTreeColorMapper:
    """
    sc.fiji.snt.analysis.MultiTreeColorMapper
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.312183
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAvailableLuts(self) -> Set[Any]: ...
    
    def getColor(self, arg0: float) -> Any: ...
    
    def getColorRGB(self, arg0: float) -> Any: ...
    
    # Multiple overloads for getColorTable
    def getColorTable(self, arg0: str) -> Any: ...
    # def getColorTable(self) -> Any: ...
    
    # Multiple overloads for getMetrics
    def getMetrics(self, arg0: str) -> List[Any]: ...
    # def getMetrics(self) -> List[Any]: ...
    
    def getMinMax(self) -> Any: ...
    
    def getMultiViewer(self) -> MultiViewer2D: ...
    
    def getNaNColor(self) -> Any: ...
    
    def getSingleValueMetrics(self) -> List[Any]: ...
    
    def isIntegerScale(self) -> bool: ...
    
    def isNodeMapping(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    # Multiple overloads for map
    def map(self, arg0: str, arg1: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: str, arg2: str) -> None: ...
    # def map(self, arg0: Tree, arg1: Profile, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: Any, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: str, arg2: Any) -> None: ...
    # def map(self, arg0: List[Any], arg1: str, arg2: str) -> None: ...
    
    def mapRootDistanceToCentroid(self, arg0: Any, arg1: Any) -> None: ...
    
    def mapTrees(self, arg0: List[Any], arg1: str) -> None: ...
    
    def setMinMax(self, arg0: float, arg1: float) -> None: ...
    
    def setNaNColor(self, arg0: Any) -> None: ...
    
    def sortedMappedTrees(self) -> List[Any]: ...
    
    # Multiple overloads for unMap
    def unMap(self, arg0: List[Any]) -> None: ...
    # def unMap(self, arg0: Tree) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class NodeColorMapper:
    """
    sc.fiji.snt.analysis.NodeColorMapper
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.350699
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAvailableLuts(self) -> Set[Any]: ...
    
    def getColor(self, arg0: float) -> Any: ...
    
    def getColorRGB(self, arg0: float) -> Any: ...
    
    # Multiple overloads for getColorTable
    def getColorTable(self) -> Any: ...
    # def getColorTable(self, arg0: str) -> Any: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def getMinMax(self) -> Any: ...
    
    def getNaNColor(self) -> Any: ...
    
    def getNodes(self) -> List[Any]: ...
    
    def getNodesByColor(self) -> Dict[str, Any]: ...
    
    def isIntegerScale(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    # Multiple overloads for map
    def map(self, arg0: str, arg1: Any) -> None: ...
    # def map(self, arg0: str, arg1: str) -> None: ...
    
    def setMinMax(self, arg0: float, arg1: float) -> None: ...
    
    def setNaNColor(self, arg0: Any) -> None: ...
    
    # Multiple overloads for unMap
    def unMap(self, arg0: List[Any]) -> None: ...
    # def unMap(self, arg0: Tree) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class NodeProfiler:
    """
    sc.fiji.snt.analysis.NodeProfiler
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.357487
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for addInput
    def addInput(self, arg0: str, arg1: type) -> Any: ...
    # def addInput(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addOutput
    def addOutput(self, arg0: Any) -> None: ...
    # def addOutput(self, arg0: str, arg1: type) -> Any: ...
    
    # Multiple overloads for cancel
    def cancel(self, arg0: str) -> None: ...
    # def cancel(self) -> None: ...
    
    def context(self) -> Any: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getDelegateObject(self) -> Any: ...
    
    # Multiple overloads for getInfo
    def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    
    def getInput(self, arg0: str) -> Any: ...
    
    def getInputs(self) -> Dict[str, Any]: ...
    
    def getOutput(self, arg0: str) -> Any: ...
    
    def getOutputs(self) -> Dict[str, Any]: ...
    
    # Multiple overloads for getPlot
    def getPlot(self, arg0: Path, arg1: int) -> Any: ...
    # def getPlot(self, arg0: Path) -> Any: ...
    
    # Multiple overloads for getTable
    def getTable(self, arg0: Path, arg1: int) -> SNTTable: ...
    # def getTable(self, arg0: Path) -> SNTTable: ...
    
    # Multiple overloads for getValues
    def getValues(self, arg0: Path, arg1: int, arg2: int) -> Any: ...
    # def getValues(self, arg0: Path) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def isCanceled(self) -> bool: ...
    
    def isInputResolved(self, arg0: str) -> bool: ...
    
    def isOutputResolved(self, arg0: str) -> bool: ...
    
    def isResolved(self, arg0: str) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def preview(self) -> None: ...
    
    def removeInput(self, arg0: Any) -> None: ...
    
    def removeOutput(self, arg0: Any) -> None: ...
    
    def resolveInput(self, arg0: str) -> None: ...
    
    def resolveOutput(self, arg0: str) -> None: ...
    
    def run(self) -> None: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: str, arg1: Any) -> None: ...
    
    def setInputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setNodeStep(self, arg0: int) -> None: ...
    
    def setOutput(self, arg0: str, arg1: Any) -> None: ...
    
    def setOutputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setRadius(self, arg0: int) -> None: ...
    
    def setResolved(self, arg0: str, arg1: bool) -> None: ...
    
    def setShape(self, arg0: Any) -> None: ...
    
    def uncancel(self) -> None: ...
    
    def unresolveInput(self, arg0: str) -> None: ...
    
    def unresolveOutput(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class NodeStatistics:
    """
    sc.fiji.snt.analysis.NodeStatistics
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.362266
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def assignBranches(self, arg0: Tree) -> None: ...
    
    def computeNearestNeighborDistances(self, arg0: List[Any]) -> None: ...
    
    def filter(self, arg0: str, arg1: float, arg2: float) -> List[Any]: ...
    
    # Multiple overloads for get
    def get(self, arg0: Any, arg1: bool) -> List[Any]: ...
    # def get(self, arg0: Any) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedFrequencies
    def getAnnotatedFrequencies(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    # def getAnnotatedFrequencies(self) -> Dict[str, Any]: ...
    # def getAnnotatedFrequencies(self, arg0: int) -> Dict[str, Any]: ...
    
    def getAnnotatedFrequenciesByHemisphere(self, arg0: int, arg1: Tree) -> Dict[str, Any]: ...
    
    def getAnnotatedFrequencyHistogram(self, arg0: int, arg1: str, arg2: Tree) -> SNTChart: ...
    
    # Multiple overloads for getAnnotatedHistogram
    def getAnnotatedHistogram(self) -> SNTChart: ...
    # def getAnnotatedHistogram(self, arg0: int) -> SNTChart: ...
    
    # Multiple overloads for getAnnotatedNodes
    def getAnnotatedNodes(self) -> Dict[str, Any]: ...
    # def getAnnotatedNodes(self, arg0: int) -> Dict[str, Any]: ...
    
    def getDescriptiveStatistics(self, arg0: str) -> Any: ...
    
    def getHistogram(self, arg0: str) -> SNTChart: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setLabel(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MultiTreeStatistics:
    """
    sc.fiji.snt.analysis.MultiTreeStatistics
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.335449
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def fromCollection(self, arg0: List[Any], arg1: str) -> TreeStatistics: ...
    
    def getAllMetrics(self) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedLength
    def getAnnotatedLength(self, arg0: int) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str, arg2: bool) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotatedLengthHistogram
    def getAnnotatedLengthHistogram(self) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int, arg1: str) -> SNTChart: ...
    
    def getAnnotatedLengthsByHemisphere(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotations
    def getAnnotations(self) -> Set[Any]: ...
    # def getAnnotations(self, arg0: int) -> Set[Any]: ...
    
    def getAvgBranchLength(self) -> float: ...
    
    def getAvgContraction(self) -> float: ...
    
    def getAvgFractalDimension(self) -> float: ...
    
    def getAvgFragmentation(self) -> float: ...
    
    def getAvgPartitionAsymmetry(self) -> float: ...
    
    def getAvgRemoteBifAngle(self) -> float: ...
    
    def getBoxPlot(self, arg0: str) -> SNTChart: ...
    
    # Multiple overloads for getBranchPoints
    def getBranchPoints(self) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any, arg1: bool) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any) -> Set[Any]: ...
    
    def getBranches(self) -> List[Any]: ...
    
    # Multiple overloads for getCableLength
    def getCableLength(self) -> float: ...
    # def getCableLength(self, arg0: Any) -> float: ...
    # def getCableLength(self, arg0: Any, arg1: bool) -> float: ...
    
    # Multiple overloads for getCableLengthNorm
    def getCableLengthNorm(self, arg0: Any) -> float: ...
    # def getCableLengthNorm(self, arg0: Any, arg1: bool) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getConvexAnalyzer(self) -> Any: ...
    
    def getConvexHullMetric(self, arg0: str) -> float: ...
    
    def getDepth(self) -> float: ...
    
    def getDescriptiveStats(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any]) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int) -> SNTChart: ...
    
    def getFractalDimension(self) -> List[Any]: ...
    
    def getGroup(self) -> List[Any]: ...
    
    def getHeight(self) -> float: ...
    
    def getHighestPathOrder(self) -> int: ...
    
    def getHistogram(self, arg0: str) -> SNTChart: ...
    
    def getInnerBranches(self) -> List[Any]: ...
    
    def getInnerLength(self) -> float: ...
    
    def getMetric(self, arg0: str) -> Union[int, float]: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathProfiler:
    """
    sc.fiji.snt.analysis.PathProfiler
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.447692
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for addInput
    def addInput(self, arg0: str, arg1: type) -> Any: ...
    # def addInput(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addOutput
    def addOutput(self, arg0: Any) -> None: ...
    # def addOutput(self, arg0: str, arg1: type) -> Any: ...
    
    # Multiple overloads for assignValues
    def assignValues(self, arg0: Path, arg1: int) -> None: ...
    # def assignValues(self, arg0: int) -> None: ...
    # def assignValues(self, arg0: Path) -> None: ...
    # def assignValues(self) -> None: ...
    
    # Multiple overloads for cancel
    def cancel(self, arg0: str) -> None: ...
    # def cancel(self) -> None: ...
    
    def context(self) -> Any: ...
    
    def findMaxima(self, arg0: Path, arg1: int) -> Any: ...
    
    def findMinima(self, arg0: Path, arg1: int) -> Any: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getDelegateObject(self) -> Any: ...
    
    # Multiple overloads for getInfo
    def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    
    def getInput(self, arg0: str) -> Any: ...
    
    def getInputs(self) -> Dict[str, Any]: ...
    
    def getOutput(self, arg0: str) -> Any: ...
    
    def getOutputs(self) -> Dict[str, Any]: ...
    
    # Multiple overloads for getPlot
    def getPlot(self, arg0: Path) -> Any: ...
    # def getPlot(self, arg0: int) -> Any: ...
    # def getPlot(self) -> Any: ...
    
    # Multiple overloads for getValues
    def getValues(self, arg0: Path) -> Dict[str, Any]: ...
    # def getValues(self, arg0: Path, arg1: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getXYPlot
    def getXYPlot(self, arg0: int) -> Any: ...
    # def getXYPlot(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def isCanceled(self) -> bool: ...
    
    def isInputResolved(self, arg0: str) -> bool: ...
    
    def isOutputResolved(self, arg0: str) -> bool: ...
    
    def isResolved(self, arg0: str) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def preview(self) -> None: ...
    
    def removeInput(self, arg0: Any) -> None: ...
    
    def removeOutput(self, arg0: Any) -> None: ...
    
    def resolveInput(self, arg0: str) -> None: ...
    
    def resolveOutput(self, arg0: str) -> None: ...
    
    def run(self) -> None: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: str, arg1: Any) -> None: ...
    
    def setInputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setMetric(self, arg0: Any) -> None: ...
    
    def setNodeIndicesAsDistances(self, arg0: bool) -> None: ...
    
    def setOutput(self, arg0: str, arg1: Any) -> None: ...
    
    def setOutputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setRadius(self, arg0: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathStatistics:
    """
    sc.fiji.snt.analysis.PathStatistics
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.471835
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def fromCollection(self, arg0: List[Any], arg1: str) -> TreeStatistics: ...
    
    def getAllMetrics(self) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedLength
    def getAnnotatedLength(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str, arg2: bool) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotatedLengthHistogram
    def getAnnotatedLengthHistogram(self) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int, arg1: str) -> SNTChart: ...
    
    def getAnnotatedLengthsByHemisphere(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotations
    def getAnnotations(self, arg0: int) -> Set[Any]: ...
    # def getAnnotations(self) -> Set[Any]: ...
    
    def getAvgBranchLength(self) -> float: ...
    
    def getAvgContraction(self) -> float: ...
    
    def getAvgFractalDimension(self) -> float: ...
    
    def getAvgFragmentation(self) -> float: ...
    
    def getAvgPartitionAsymmetry(self) -> float: ...
    
    def getAvgRemoteBifAngle(self) -> float: ...
    
    # Multiple overloads for getBranchPoints
    def getBranchPoints(self, arg0: Any, arg1: bool) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any) -> Set[Any]: ...
    # def getBranchPoints(self) -> Set[Any]: ...
    
    def getBranches(self) -> List[Any]: ...
    
    # Multiple overloads for getCableLength
    def getCableLength(self, arg0: Any) -> float: ...
    # def getCableLength(self) -> float: ...
    # def getCableLength(self, arg0: Any, arg1: bool) -> float: ...
    
    # Multiple overloads for getCableLengthNorm
    def getCableLengthNorm(self, arg0: Any) -> float: ...
    # def getCableLengthNorm(self, arg0: Any, arg1: bool) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getConvexAnalyzer(self) -> Any: ...
    
    def getConvexHullMetric(self, arg0: str) -> float: ...
    
    def getDepth(self) -> float: ...
    
    def getDescriptiveStats(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any]) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> SNTChart: ...
    
    def getFractalDimension(self) -> List[Any]: ...
    
    def getHeight(self) -> float: ...
    
    def getHighestPathOrder(self) -> int: ...
    
    def getHistogram(self, arg0: str) -> SNTChart: ...
    
    def getInnerBranches(self) -> List[Any]: ...
    
    def getInnerLength(self) -> float: ...
    
    # Multiple overloads for getMetric
    def getMetric(self, arg0: str, arg1: Path) -> Union[int, float]: ...
    # def getMetric(self, arg0: str) -> Union[int, float]: ...
    
    # Multiple overloads for getMetrics
    def getMetrics(self, arg0: str) -> List[Any]: ...
    # def getMetrics(self) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathStraightener:
    """
    sc.fiji.snt.analysis.PathStraightener
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.474995
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setWidth(self, arg0: int) -> None: ...
    
    # Multiple overloads for straighten
    def straighten(self) -> Any: ...
    # def straighten(self, arg0: int) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PCAnalyzer:
    """
    sc.fiji.snt.analysis.PCAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.365701
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for getPrincipalAxes
    def getPrincipalAxes(self, arg0: Any) -> Any: ...
    # def getPrincipalAxes(self, arg0: Path) -> Any: ...
    # def getPrincipalAxes(self, arg0: Tree, arg1: bool) -> Any: ...
    # def getPrincipalAxes(self, arg0: Tree) -> Any: ...
    # def getPrincipalAxes(self, arg0: List[Any]) -> Any: ...
    
    def getVariancePercentages(self, arg0: Any) -> Any: ...
    
    def orientTowardDirection(self, arg0: Any, arg1: Any) -> Any: ...
    
    def orientTowardTips(self, arg0: Any, arg1: Tree) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PersistenceAnalyzer:
    """
    sc.fiji.snt.analysis.PersistenceAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.477175
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getBarcode(self, arg0: str) -> List[Any]: ...
    
    def getDescriptors(self) -> List[Any]: ...
    
    def getDiagram(self, arg0: str) -> List[Any]: ...
    
    def getDiagramNodes(self, arg0: str) -> List[Any]: ...
    
    def getLandscape(self, arg0: str, arg1: int, arg2: int) -> Any: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class RootAngleAnalyzer:
    """
    sc.fiji.snt.analysis.RootAngleAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.488966
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def balancingFactor(self) -> float: ...
    
    def centripetalBias(self) -> float: ...
    
    def getAnalysis(self) -> Dict[str, Any]: ...
    
    def getAngles(self) -> List[Any]: ...
    
    def getCramerVonMisesStatistic(self) -> float: ...
    
    def getDensityPlot(self, arg0: List[Any]) -> SNTChart: ...
    
    def getDensityPlot(self) -> SNTChart: ...
    
    def getDescriptiveStatistics(self) -> Any: ...
    
    def getHistogram(self, arg0: List[Any], arg1: bool) -> SNTChart: ...
    
    def getHistogram(self, arg0: bool) -> SNTChart: ...
    
    def getTaggedGraph(self) -> DirectedWeightedGraph: ...
    
    # Multiple overloads for getTaggedTree
    def getTaggedTree(self, arg0: Any) -> Tree: ...
    # def getTaggedTree(self) -> Tree: ...
    # def getTaggedTree(self, arg0: str, arg1: float, arg2: float) -> Tree: ...
    # def getTaggedTree(self, arg0: Any, arg1: float, arg2: float) -> Tree: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def max(self) -> float: ...
    
    def mean(self) -> float: ...
    
    def meanDirection(self) -> float: ...
    
    def min(self) -> float: ...
    
    def supportedMetrics(self) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TreeColorMapper:
    """
    sc.fiji.snt.analysis.TreeColorMapper
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.733259
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAvailableLuts(self) -> Set[Any]: ...
    
    def getColor(self, arg0: float) -> Any: ...
    
    def getColorRGB(self, arg0: float) -> Any: ...
    
    # Multiple overloads for getColorTable
    def getColorTable(self, arg0: str) -> Any: ...
    # def getColorTable(self) -> Any: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def getMinMax(self) -> Any: ...
    
    def getMultiViewer(self) -> MultiViewer2D: ...
    
    def getNaNColor(self) -> Any: ...
    
    def isIntegerScale(self) -> bool: ...
    
    def isNodeMapping(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    # Multiple overloads for map
    def map(self, arg0: Tree, arg1: str, arg2: str) -> None: ...
    # def map(self, arg0: Tree, arg1: Profile, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: Any, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: str, arg2: Any) -> None: ...
    # def map(self, arg0: List[Any], arg1: str, arg2: str) -> None: ...
    # def map(self, arg0: str, arg1: Any) -> None: ...
    
    def mapTrees(self, arg0: List[Any], arg1: str) -> None: ...
    
    def setMinMax(self, arg0: float, arg1: float) -> None: ...
    
    def setNaNColor(self, arg0: Any) -> None: ...
    
    # Multiple overloads for unMap
    def unMap(self, arg0: List[Any]) -> None: ...
    # def unMap(self, arg0: Tree) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TreeStatistics:
    """
    sc.fiji.snt.analysis.TreeStatistics
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.758116
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def cancel(self, arg0: str) -> None: ...
    
    def context(self) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def fromCollection(self, arg0: List[Any], arg1: str) -> TreeStatistics: ...
    
    def getAllMetrics(self) -> List[Any]: ...
    
    # Multiple overloads for getAnnotatedLength
    def getAnnotatedLength(self, arg0: int, arg1: str) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int, arg1: str, arg2: bool) -> Dict[str, Any]: ...
    # def getAnnotatedLength(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotatedLengthHistogram
    def getAnnotatedLengthHistogram(self) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int) -> SNTChart: ...
    # def getAnnotatedLengthHistogram(self, arg0: int, arg1: str) -> SNTChart: ...
    
    def getAnnotatedLengthsByHemisphere(self, arg0: int) -> Dict[str, Any]: ...
    
    # Multiple overloads for getAnnotations
    def getAnnotations(self, arg0: int) -> Set[Any]: ...
    # def getAnnotations(self) -> Set[Any]: ...
    
    def getAvgBranchLength(self) -> float: ...
    
    def getAvgContraction(self) -> float: ...
    
    def getAvgFractalDimension(self) -> float: ...
    
    def getAvgFragmentation(self) -> float: ...
    
    def getAvgPartitionAsymmetry(self) -> float: ...
    
    def getAvgRemoteBifAngle(self) -> float: ...
    
    # Multiple overloads for getBranchPoints
    def getBranchPoints(self, arg0: Any, arg1: bool) -> Set[Any]: ...
    # def getBranchPoints(self, arg0: Any) -> Set[Any]: ...
    # def getBranchPoints(self) -> Set[Any]: ...
    
    def getBranches(self) -> List[Any]: ...
    
    # Multiple overloads for getCableLength
    def getCableLength(self, arg0: Any) -> float: ...
    # def getCableLength(self) -> float: ...
    # def getCableLength(self, arg0: Any, arg1: bool) -> float: ...
    
    # Multiple overloads for getCableLengthNorm
    def getCableLengthNorm(self, arg0: Any) -> float: ...
    # def getCableLengthNorm(self, arg0: Any, arg1: bool) -> float: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getConvexAnalyzer(self) -> Any: ...
    
    def getConvexHullMetric(self, arg0: str) -> float: ...
    
    def getDepth(self) -> float: ...
    
    def getDescriptiveStats(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getFlowPlot
    def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: str, arg3: float, arg4: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any]) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: List[Any], arg2: bool) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int) -> SNTChart: ...
    # def getFlowPlot(self, arg0: str, arg1: int, arg2: float, arg3: bool) -> SNTChart: ...
    
    def getFractalDimension(self) -> List[Any]: ...
    
    def getHeight(self) -> float: ...
    
    def getHighestPathOrder(self) -> int: ...
    
    def getHistogram(self, arg0: str) -> SNTChart: ...
    
    def getInnerBranches(self) -> List[Any]: ...
    
    def getInnerLength(self) -> float: ...
    
    def getMetric(self, arg0: str) -> Union[int, float]: ...
    
    # Multiple overloads for getMetrics
    def getMetrics(self, arg0: str) -> List[Any]: ...
    # def getMetrics(self) -> List[Any]: ...
    
    def getNBranchPoints(self, arg0: Any, arg1: bool) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ShollAnalyzer:
    """
    sc.fiji.snt.analysis.ShollAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.658760
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getLinearStats(self) -> Any: ...
    
    def getMaximaRadii(self) -> List[Any]: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def getNormStats(self) -> Any: ...
    
    def getSecondaryMaxima(self) -> List[Any]: ...
    
    def getSingleValueMetrics(self) -> Dict[str, Any]: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setEnableCurveFitting(self, arg0: bool) -> None: ...
    
    def setPolynomialFitRange(self, arg0: int, arg1: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SkeletonConverter:
    """
    sc.fiji.snt.analysis.SkeletonConverter
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.665963
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getGraphs(self) -> List[Any]: ...
    
    def getPruneMode(self) -> int: ...
    
    def getRootRoiStrategy(self) -> int: ...
    
    def getSingleGraph(self) -> DirectedWeightedGraph: ...
    
    def getSingleTree(self) -> Tree: ...
    
    def getTrees(self) -> List[Any]: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setConnectComponents(self, arg0: bool) -> None: ...
    
    def setLengthThreshold(self, arg0: float) -> None: ...
    
    def setMaxConnectDist(self, arg0: float) -> None: ...
    
    def setOrigIP(self, arg0: Any) -> None: ...
    
    def setPruneByLength(self, arg0: bool) -> None: ...
    
    def setPruneEnds(self, arg0: bool) -> None: ...
    
    def setPruneMode(self, arg0: int) -> None: ...
    
    def setRootRoi(self, arg0: Any, arg1: int) -> None: ...
    
    def setShortestPath(self, arg0: bool) -> None: ...
    
    def setSilent(self, arg0: bool) -> None: ...
    
    def setVerbose(self, arg0: bool) -> None: ...
    
    # Multiple overloads for skeletonize
    def skeletonize(self, arg0: Any, arg1: bool) -> None: ...
    # def skeletonize(self, arg0: Any, arg1: float, arg2: float, arg3: bool) -> None: ...
    
    def skeletonizeTimeLapse(self, arg0: Any, arg1: bool) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class StrahlerAnalyzer:
    """
    sc.fiji.snt.analysis.StrahlerAnalyzer
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.670454
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def classify(self, arg0: DirectedWeightedGraph, arg1: bool) -> None: ...
    
    def dispose(self) -> None: ...
    
    def getAvgBifurcationRatio(self) -> float: ...
    
    def getAvgContractions(self) -> Dict[str, Any]: ...
    
    def getAvgExtensionAngle(self, arg0: bool, arg1: int) -> float: ...
    
    def getAvgExtensionAngles(self, arg0: bool) -> Dict[str, Any]: ...
    
    def getAvgFragmentations(self) -> Dict[str, Any]: ...
    
    def getBifurcationRatios(self) -> Dict[str, Any]: ...
    
    def getBranchCounts(self) -> Dict[str, Any]: ...
    
    def getBranchPointCounts(self) -> Dict[str, Any]: ...
    
    # Multiple overloads for getBranches
    def getBranches(self) -> Dict[str, Any]: ...
    # def getBranches(self, arg0: int) -> List[Any]: ...
    
    def getExtensionAngles(self, arg0: bool) -> Dict[str, Any]: ...
    
    def getGraph(self) -> DirectedWeightedGraph: ...
    
    def getHighestBranchOrder(self) -> int: ...
    
    def getLengths(self) -> Dict[str, Any]: ...
    
    def getRelativeExtensionAngle(self, arg0: Path) -> float: ...
    
    def getRootAssociatedBranches(self) -> List[Any]: ...
    
    def getRootNumber(self) -> int: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTChart:
    """
    sc.fiji.snt.analysis.SNTChart
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.561270
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    def actionPerformed(self, arg0: Any) -> None: ...
    
    # Multiple overloads for add
    def add(self, arg0: str, arg1: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: int) -> Any: ...
    # def add(self, arg0: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: Any) -> None: ...
    # def add(self, arg0: Any, arg1: Any, arg2: int) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    
    def addAncestorListener(self, arg0: Any) -> None: ...
    
    def addChartMouseListener(self, arg0: Any) -> None: ...
    
    def addColorBarLegend(self, arg0: str, arg1: Any, arg2: float, arg3: float, arg4: int) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addContainerListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    def addOverlay(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addPolygon
    def addPolygon(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...
    # def addPolygon(self, arg0: Any, arg1: str, arg2: str) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: Any) -> None: ...
    
    def addVetoableChangeListener(self, arg0: Any) -> None: ...
    
    # Multiple overloads for annotate
    def annotate(self, arg0: str) -> None: ...
    # def annotate(self, arg0: str, arg1: str, arg2: str) -> None: ...
    
    # Multiple overloads for annotateCategory
    def annotateCategory(self, arg0: str, arg1: str, arg2: str) -> None: ...
    # def annotateCategory(self, arg0: str, arg1: str) -> None: ...
    
    # Multiple overloads for annotatePoint
    def annotatePoint(self, arg0: Any, arg1: str, arg2: str) -> None: ...
    # def annotatePoint(self, arg0: float, arg1: float, arg2: str, arg3: str) -> None: ...
    # def annotatePoint(self, arg0: float, arg1: float, arg2: str) -> None: ...
    
    # Multiple overloads for annotateXline
    def annotateXline(self, arg0: float, arg1: str, arg2: str) -> None: ...
    # def annotateXline(self, arg0: float, arg1: str) -> None: ...
    
    # Multiple overloads for annotateYline
    def annotateYline(self, arg0: float, arg1: str) -> None: ...
    # def annotateYline(self, arg0: float, arg1: str, arg2: str) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    def applyStyle(self, arg0: SNTChart) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    def chartChanged(self, arg0: Any) -> None: ...
    
    def chartProgress(self, arg0: Any) -> None: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    def closeAll(self) -> None: ...
    
    # Multiple overloads for combine
    def combine(self, arg0: List[Any], arg1: int, arg2: int, arg3: bool) -> SNTChart: ...
    # def combine(self, arg0: List[Any], arg1: str, arg2: int, arg3: int, arg4: bool) -> SNTChart: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTTable:
    """
    sc.fiji.snt.analysis.SNTTable
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.591093
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for add
    def add(self, arg0: int, arg1: Any) -> None: ...
    # def add(self, arg0: Any) -> bool: ...
    # def add(self, arg0: int, arg1: Any) -> None: ...
    # def add(self, arg0: Any) -> bool: ...
    
    # Multiple overloads for addAll
    def addAll(self, arg0: List[Any]) -> bool: ...
    # def addAll(self, arg0: int, arg1: List[Any]) -> bool: ...
    
    # Multiple overloads for addColumn
    def addColumn(self, arg0: str, arg1: List[Any]) -> None: ...
    # def addColumn(self, arg0: str, arg1: Any) -> None: ...
    
    def addFirst(self, arg0: Any) -> None: ...
    
    def addGenericColumn(self, arg0: str, arg1: List[Any]) -> None: ...
    
    def addLast(self, arg0: Any) -> None: ...
    
    # Multiple overloads for appendColumn
    def appendColumn(self) -> Any: ...
    # def appendColumn(self, arg0: str) -> Any: ...
    
    # Multiple overloads for appendColumns
    def appendColumns(self, arg0: Any) -> List[Any]: ...
    # def appendColumns(self, arg0: int) -> List[Any]: ...
    
    # Multiple overloads for appendRow
    def appendRow(self, arg0: str) -> None: ...
    # def appendRow(self) -> None: ...
    
    # Multiple overloads for appendRows
    def appendRows(self, arg0: Any) -> None: ...
    # def appendRows(self, arg0: int) -> None: ...
    
    def appendToLastRow(self, arg0: str, arg1: Any) -> None: ...
    
    def clear(self) -> None: ...
    
    def clone(self) -> Any: ...
    
    def contains(self, arg0: Any) -> bool: ...
    
    def containsAll(self, arg0: List[Any]) -> bool: ...
    
    def createOrUpdateDisplay(self) -> None: ...
    
    def ensureCapacity(self, arg0: int) -> None: ...
    
    def fillEmptyCells(self, arg0: Any) -> None: ...
    
    def forEach(self, arg0: Any) -> None: ...
    
    # Multiple overloads for fromFile
    def fromFile(self, arg0: str, arg1: str) -> SNTTable: ...
    # def fromFile(self, arg0: str) -> SNTTable: ...
    
    # Multiple overloads for geColumnHeaders
    def geColumnHeaders(self) -> List[Any]: ...
    # def geColumnHeaders(self, arg0: str) -> List[Any]: ...
    
    # Multiple overloads for geColumnStats
    def geColumnStats(self, arg0: int, arg1: int, arg2: int) -> Any: ...
    # def geColumnStats(self, arg0: str, arg1: int, arg2: int) -> Any: ...
    
    # Multiple overloads for geRowStats
    def geRowStats(self, arg0: str, arg1: int, arg2: int) -> Any: ...
    # def geRowStats(self, arg0: int, arg1: int, arg2: int) -> Any: ...
    
    # Multiple overloads for get
    def get(self, arg0: int) -> Any: ...
    # def get(self, arg0: int) -> Any: ...
    # def get(self, arg0: str) -> Any: ...
    # def get(self, arg0: str, arg1: int) -> Any: ...
    # def get(self, arg0: int, arg1: int) -> Any: ...
    
    def getColumnCount(self) -> int: ...
    
    def getColumnHeader(self, arg0: int) -> str: ...
    
    def getColumnIndex(self, arg0: str) -> int: ...
    
    def getFirst(self) -> Any: ...
    
    def getLast(self) -> Any: ...
    
    def getRowCount(self) -> int: ...
    
    def getRowHeader(self, arg0: int) -> str: ...
    
    def getRowIndex(self, arg0: str) -> int: ...
    
    def getSummaryRow(self) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def growth(*args: Any, **kwargs: Any) -> Any: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Callable: ...
class Dict: ...
class List: ...