# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      # Workaround timezone issues that can affect Jupyter dependencies
      - export TZ=UTC
      - export LC_ALL=C.UTF-8
      - export LANG=C.UTF-8
    post_create_environment:
      - pip install --upgrade pip setuptools wheel
    post_install:
      - echo "Build environment ready"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Don't fail the build on Sphinx warnings
  fail_on_warning: false

# We don't execute notebooks on RTD; they render from stored outputs.
# Notebook execution is controlled inside docs/conf.py (nb_execution_mode = "off")
python:
  install:
    # Install documentation-specific requirements
    - requirements: docs/requirements.txt
    # Install the package itself with docs extras
    - method: pip
      path: .
      extra_requirements:
        - docs

# Optional
formats:
  - pdf
  - htmlzip
