# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install the package in editable mode for autodoc
      - pip install -e .
    post_install:
      # Ensure all dependencies are available
      - pip install --upgrade pip

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# We don't execute notebooks on RTD; they render from stored outputs.
# Notebook execution is controlled inside docs/conf.py (nb_execution_mode = "off")
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .