# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# We don't execute notebooks on RTD; they render from stored outputs.
# Notebook execution is controlled inside docs/conf.py (nb_execution_mode = "off")
python:
  install:
    - requirements: docs/requirements.txt