name: pysnt
channels:
  - conda-forge
  - defaults
dependencies:
  # Core runtime dependencies
  - python>=3.8
  - openjdk=21
  - scyjava>=1.12.1
  - pyimagej>=1.7.0
  - install-jdk>=1.1.0
  - numpy>=2.3.3
  - matplotlib>=3.10.7
  - xarray>=2025.10.1

  # Optional dependencies for enhanced features
  - pandas>=2.3.3
  - networkx>=3.0

  # macOS-specific dependencies
  - pyobjc-core  # [osx]
  - pyobjc-framework-cocoa  # [osx]

  # Pip dependencies (runtime only)
  - pip
