"""
Type stubs for core.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
def _add_metadata(kwargs: Any, **metadata_updates: Any) -> Any: ...

def _is_java_type(obj: Any, *type_names: Any) -> Any: ...

def handle_display_errors(operation_name: str) -> Any: ...

def _convert_objects_to_figures(obj_list: Any, converter_func: Any, obj_type_name: Any, **kwargs: Any) -> Any: ...

def _extract_title(obj: Any, default_title: Any) -> Any: ...

def _create_combined_figure(figures: Any, titles: Any, obj_type_name: Any, obj_count: Any, **kwargs: Any) -> Any: ...

def _limit_list_size(obj_list: Any, obj_type_name: Any, max_panels: Any) -> Any: ...

def _display_typed_list(obj_list: Any, converter_func: Any, type_name: Any, show: Any, **kwargs: Any) -> Any: ...

def _classify_objects_for_list_display(obj_list: Any) -> Any: ...

def _get_single_type_handler(classified: Any) -> Any: ...

def _get_priority_handler(classified: Any) -> Any: ...

def _convert_viewer2d_to_chart(viewer2d: Any, **kwargs: Any) -> Any: ...

def _convert_imageplus_to_xarray(imageplus: Any, index: Any, **kwargs: Any) -> Any: ...

def _calculate_figure_size(aspect_ratios: Any, panel_layout: Any, num_panels: Any) -> Any: ...

def _plot_image_panel(ax: Any, xarray_data: Any, metadata: Any, image_title: Any, **kwargs: Any) -> Any: ...

def _apply_figure_layout(fig: Any, title: Any, **kwargs: Any) -> Any: ...

def display(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _tree_to_chart(obj: Any) -> Any: ...

def _get_display_handler(obj: Any) -> Tuple[str, Optional[Callable]]: ...

def _handle_snt_object_display(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_snt_table(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_snt_chart(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_snt_graph(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _is_viewer3d(obj: Any) -> bool: ...

def _is_viewer2d(obj: Any) -> bool: ...

def _display_viewer3d(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_viewer3d_orthoview(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_viewer2d(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_imglib2_rai(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_imgplus(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_networkx_graph(graph: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_with_auto_conversion(obj: Any, show: bool, **kwargs: Any) -> Any: ...

def _display_generic_object(obj: Any, **kwargs: Any) -> Any: ...

def _display_object_list(obj_list: list, show: bool, **kwargs: Any) -> Any: ...

def _preprocess_object_list(obj_list: Any) -> Any: ...

def _display_snt_chart_list(chart_list: list, show: bool, **kwargs: Any) -> Any: ...

def _display_viewer2d_list(viewer2d_list: list, show: bool, **kwargs: Any) -> Any: ...

def _display_tree_list(tree_list: list, show: bool, **kwargs: Any) -> Any: ...

def _display_imgplus_list(imgplus_list: list, show: bool, **kwargs: Any) -> Any: ...

def _display_matplotlib_figure_list(figure_list: list, figure_source_types: list, show: bool, **kwargs: Any) -> Any: ...

def _display_imageplus_list(imageplus_list: list, show: bool, **kwargs: Any) -> Any: ...
