"""
Type stubs for core.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
def handle_display_errors(operation_name: str) -> Any: ...

def _convert_objects_to_figures(obj_list: Any, converter_func: Any, obj_type_name: Any, **kwargs: Any) -> Any: ...

def _convert_viewer2d_to_chart(viewer2d: Any, **kwargs: Any) -> Any: ...

def _convert_imageplus_to_xarray(imageplus: Any, index: Any, **kwargs: Any) -> Any: ...

def _calculate_figure_size(aspect_ratios: Any, panel_layout: Any, num_panels: Any) -> Any: ...

def _plot_image_panel(ax: Any, xarray_data: Any, metadata: Any, image_title: Any, **kwargs: Any) -> Any: ...

def _apply_figure_layout(fig: Any, title: Any, **kwargs: Any) -> Any: ...

def _create_combined_figure(figures: Any, titles: Any, obj_type_name: Any, obj_count: Any, **kwargs: Any) -> Any: ...

def display(obj: Any, **kwargs: Any) -> Any: ...

def _tree_to_chart(obj: Any) -> Any: ...

def _get_display_handler(obj: Any) -> Tuple[str, Optional[Callable]]: ...

def _handle_snt_object_display(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_table(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_chart(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_graph(obj: Any, **kwargs: Any) -> Any: ...

def _display_with_auto_conversion(obj: Any, **kwargs: Any) -> Any: ...

def _display_generic_object(obj: Any, **kwargs: Any) -> Any: ...

def _display_object_list(obj_list: list, **kwargs: Any) -> Any: ...

def _display_snt_chart_list(chart_list: list, **kwargs: Any) -> Any: ...

def _display_viewer2d_list(viewer2d_list: list, **kwargs: Any) -> Any: ...

def _display_tree_list(tree_list: list, **kwargs: Any) -> Any: ...

def _display_imageplus_list(imageplus_list: list, **kwargs: Any) -> Any: ...

def _is_viewer3d(obj: Any) -> bool: ...

def _display_viewer3d(obj: Any, **kwargs: Any) -> Any: ...

def _display_viewer3d_orthoview(obj: Any, **kwargs: Any) -> Any: ...

def _is_viewer2d(obj: Any) -> bool: ...

def _display_viewer2d(obj: Any, **kwargs: Any) -> Any: ...

def _display_networkx_graph(graph: Any, **kwargs: Any) -> Any: ...
