"""
Type stubs for core.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
def display(obj: Any, **kwargs: Any) -> Any: ...

def _get_display_handler(obj: Any) -> Tuple[str, Optional[Callable]]: ...

def _handle_snt_object_display(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_table(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_chart(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_graph(obj: Any, **kwargs: Any) -> Any: ...

def _display_with_auto_conversion(obj: Any, **kwargs: Any) -> Any: ...

def _display_generic_object(obj: Any, **kwargs: Any) -> Any: ...

def _display_object_list(obj_list: list, **kwargs: Any) -> Any: ...

def _display_snt_chart_list(chart_list: list, **kwargs: Any) -> Any: ...
