"""
Type stubs for utils.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable

logger: Any
_DISPLAY_HANDLERS: Any
def _get_pandasgui_show() -> Any: ...

def _has_pandasgui() -> Any: ...

def _is_snt_object(obj: Any) -> bool: ...

def _is_snt_tree(obj: Any) -> bool: ...

def _is_snt_path(obj: Any) -> bool: ...

def _is_xarray_object(obj: Any) -> bool: ...

def _extract_display_config(**kwargs: Any) -> Dict[str, Any]: ...

def _handle_display_error(error: Exception, operation: str, obj_type: str) -> None: ...

def _validate_display_kwargs(**kwargs: Any) -> Dict[str, Any]: ...

def register_display_handler(obj_type: str, handler_func: Any) -> Any: ...
