"""
Type stubs for utils.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
_DISPLAY_HANDLERS: Any
def _get_pandasgui_show() -> Any: ...
def _has_pandasgui() -> Any: ...
def _is_snt_object(obj: Any) -> bool: ...
def _is_snt_tree(obj: Any) -> bool: ...
def _is_snt_path(obj: Any) -> bool: ...
def _is_xarray_object(obj: Any) -> bool: ...
def _extract_display_config(**kwargs: Any) -> Dict[str, Any]: ...
def _handle_display_error(error: Exception, operation: str, obj_type: str) -> None: ...
def _validate_display_kwargs(**kwargs: Any) -> Dict[str, Any]: ...
def _hide_axis_decorations(ax: Any, hide_axis_completely: Any) -> Any: ...
def _setup_clean_axis(ax: Any, title: Any, show_title: Any, hide_axis_completely: Any) -> Any: ...
def _apply_standard_layout(fig: Any, show_overall_title: Any, show_panel_titles: Any, overall_title: Any) -> Any: ...
def _create_subplot_grid(num_panels: Any, panel_layout: Any, figsize: Any, source_figures: Any) -> Any: ...
def register_display_handler(obj_type: str, handler_func: Any) -> Any: ...

# Constants imported from converters.core
DEFAULT_CMAP: str
DEFAULT_NODE_COLOR: str
DEFAULT_NODE_SIZE: int
ERROR_MISSING_NETWORKX: str

# Functions imported from converters.core
def _create_standard_figure(data: Any, title: Optional[str] = None, cmap: str = 'viridis', add_colorbar: bool = True, is_rgb: bool = False, **kwargs: Any) -> tuple[Any, Any, Any]: ...
def _extract_color_attributes(color: Any, attr_name: str) -> Dict[str, Any]: ...
def _setup_matplotlib_interactive() -> Any: ...

def _hide_axis_decorations(ax: Any, hide_axis_completely: bool = False) -> None: ...
def _setup_clean_axis(ax: Any, title: Optional[str] = None, show_title: bool = True, hide_axis_completely: bool = False) -> None: ...
def _apply_standard_layout(fig: Any, show_overall_title: bool = False, show_panel_titles: bool = False, overall_title: Optional[str] = None) -> None: ...
def _create_subplot_grid(num_panels: int, panel_layout: Union[str, tuple[int, int]] = "auto", figsize: Optional[tuple[float, float]] = None, source_figures: Optional[List[Any]] = None) -> tuple[Any, List[Any], tuple[int, int]]: ...