"""
Type stubs for visual_display.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
def _display_matplotlib_figure(fig: Figure, **kwargs: Any) -> None: ...

def _show_matplotlib_figure(fig: Any, **kwargs: Any) -> bool: ...

def _get_default_layout_for_graph_type(graph_type: str) -> str: ...

def _graph_to_matplotlib(graph: Any, **kwargs: Any) -> Figure: ...

def _display_array_data(data: Any, source_type: Any, **kwargs: Any) -> Any: ...

def _should_preserve_aspect(image_array: Any) -> Any: ...

def _combine_matplotlib_figures(figures: list, titles: list, overall_title: str, **kwargs: Any) -> Figure: ...
