"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable

class BiSearchArtist:
    """
    SNT BiSearchArtist class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...

    # Methods
    def anyNodeUnderThreshold(self, arg0: int, arg1: int, arg2: int, arg3: float) -> Any: ...
    def drawProgressOnSlice(self, arg0: int, arg1: int, arg2: Any, arg3: Any) -> None: ...
    def getSearch(self) -> Any: ...
    def setClosedColor(self, arg0: Any) -> None: ...
    def setDrawingThreshold(self, arg0: float) -> None: ...
    def setOpenColor(self, arg0: Any) -> None: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class FillerThreadArtist:
    """
    SNT FillerThreadArtist class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...

    # Methods
    def anyNodeUnderThreshold(self, arg0: int, arg1: int, arg2: int, arg3: float) -> Any: ...
    def drawProgressOnSlice(self, arg0: int, arg1: int, arg2: Any, arg3: Any) -> None: ...
    def getSearch(self) -> Any: ...
    def setClosedColor(self, arg0: Any) -> None: ...
    def setOpacity(self, arg0: float) -> None: ...
    def setOpenColor(self, arg0: Any) -> None: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class SearchArtistFactory:
    """
    SNT SearchArtistFactory class with complete method signatures.
    Generated using Java reflection.
    """

    def __init__(self) -> None:
        """Initialize SearchArtistFactory."""
        ...

    # Methods
    @overload
    def create(self, arg0: Any) -> Any: ...
    @overload
    def create(self, arg0: Any) -> Any: ...
    @overload
    def create(self, arg0: Any) -> Any: ...
    @overload
    def create(self, arg0: Any) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class SearchThreadArtist:
    """
    SNT SearchThreadArtist class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...

    # Methods
    def anyNodeUnderThreshold(self, arg0: int, arg1: int, arg2: int, arg3: float) -> Any: ...
    def drawProgressOnSlice(self, arg0: int, arg1: int, arg2: Any, arg3: Any) -> None: ...
    def getSearch(self) -> Any: ...
    def setClosedColor(self, arg0: Any) -> None: ...
    def setDrawingThreshold(self, arg0: float) -> None: ...
    def setOpenColor(self, arg0: Any) -> None: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...


# Other functions
def get_available_classes() -> Any: ...
def get_class(class_name: str) -> Any: ...
def get_curated_classes() -> Any: ...
def get_extended_classes() -> Any: ...
def list_classes() -> None: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...

# Constants
CURATED_CLASSES: List[str]
EXTENDED_CLASSES: List[str]