"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class Frangi:
    """
    sc.fiji.snt.filter.Frangi
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:34:38.069710
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for accept
    def accept(self, arg0: Any) -> None: ...
    # def accept(self, arg0: Any) -> None: ...
    
    def andThen(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for apply
    def apply(self, arg0: Any, arg1: Any, arg2: float, arg3: int) -> Any: ...
    # def apply(self, arg0: Any, arg1: Any) -> Any: ...
    
    # Multiple overloads for compute
    def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any) -> None: ...
    
    def getArity(self) -> int: ...
    
    # Multiple overloads for getIndependentInstance
    def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    
    def in(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def ops(self) -> Any: ...
    
    def out(self) -> Any: ...
    
    # Multiple overloads for run
    def run(self) -> None: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any, arg1: Any) -> Any: ...
    
    def setEnvironment(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: Any) -> None: ...
    
    def setOutput(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Tubeness:
    """
    sc.fiji.snt.filter.Tubeness
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:34:38.075557
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for accept
    def accept(self, arg0: Any) -> None: ...
    # def accept(self, arg0: Any) -> None: ...
    
    def andThen(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for apply
    def apply(self, arg0: Any, arg1: float) -> Any: ...
    # def apply(self, arg0: Any, arg1: Any) -> Any: ...
    # def apply(self, arg0: Any, arg1: Any, arg2: int) -> Any: ...
    
    # Multiple overloads for compute
    def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any) -> None: ...
    
    def getArity(self) -> int: ...
    
    # Multiple overloads for getIndependentInstance
    def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    
    def in(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def ops(self) -> Any: ...
    
    def out(self) -> Any: ...
    
    # Multiple overloads for run
    def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self) -> None: ...
    # def run(self, arg0: Any, arg1: Any) -> Any: ...
    
    def setEnvironment(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: Any) -> None: ...
    
    def setOutput(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...