"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class Frangi:
    """
    sc.fiji.snt.filter.Frangi
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:00:58.414392
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for accept
    def accept(self, arg0: Any) -> None: ...
    # def accept(self, arg0: Any) -> None: ...
    
    def andThen(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for apply
    def apply(self, arg0: Any, arg1: Any, arg2: float, arg3: int) -> Any: ...
    # def apply(self, arg0: Any, arg1: Any) -> Any: ...
    
    # Multiple overloads for compute
    def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any) -> None: ...
    
    def getArity(self) -> int: ...
    
    # Multiple overloads for getIndependentInstance
    def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    
    def in(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def ops(self) -> Any: ...
    
    def out(self) -> Any: ...
    
    # Multiple overloads for run
    def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self) -> None: ...
    # def run(self, arg0: Any, arg1: Any) -> Any: ...
    
    def setEnvironment(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: Any) -> None: ...
    
    def setOutput(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Tubeness:
    """
    sc.fiji.snt.filter.Tubeness
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:12.293786
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for accept
    def accept(self, arg0: Any) -> None: ...
    # def accept(self, arg0: Any) -> None: ...
    
    def andThen(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for apply
    def apply(self, arg0: Any, arg1: Any) -> Any: ...
    # def apply(self, arg0: Any, arg1: Any, arg2: int) -> Any: ...
    # def apply(self, arg0: Any, arg1: float) -> Any: ...
    
    # Multiple overloads for compute
    def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any) -> None: ...
    
    def getArity(self) -> int: ...
    
    # Multiple overloads for getIndependentInstance
    def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    
    def in(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    def ops(self) -> Any: ...
    
    def out(self) -> Any: ...
    
    # Multiple overloads for run
    def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self) -> None: ...
    # def run(self, arg0: Any, arg1: Any) -> Any: ...
    
    def setEnvironment(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: Any) -> None: ...
    
    def setOutput(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SpectralSimilarity:
    """
    sc.fiji.snt.filter.SpectralSimilarity
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:10.806394
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for accept
    def accept(self, arg0: Any) -> None: ...
    # def accept(self, arg0: Any) -> None: ...
    
    def andThen(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for averageColorAtPositions
    def averageColorAtPositions(self, arg0: Any, arg1: Any) -> Any: ...
    # def averageColorAtPositions(self, arg0: Any, arg1: Any) -> Any: ...
    
    # Multiple overloads for averageColorFromPaths
    def averageColorFromPaths(self, arg0: Any, arg1: List[Any], arg2: float, arg3: float, arg4: float) -> Any: ...
    # def averageColorFromPaths(self, arg0: Any, arg1: List[Any], arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float) -> Any: ...
    
    def channelSum(self, arg0: Any) -> float: ...
    
    # Multiple overloads for compute
    def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any, arg1: Any) -> None: ...
    # def compute(self, arg0: Any) -> None: ...
    
    def getArity(self) -> int: ...
    
    # Multiple overloads for getIndependentInstance
    def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    # def getIndependentInstance(self) -> Any: ...
    
    def getReferenceColor(self) -> Any: ...
    
    def in(self) -> Any: ...
    
    def initialize(self) -> None: ...
    
    # Multiple overloads for nodeToPixelCoords
    def nodeToPixelCoords(self, arg0: PointInImage, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float) -> Any: ...
    # def nodeToPixelCoords(self, arg0: PointInImage, arg1: float, arg2: float, arg3: float) -> Any: ...
    
    def normalizeVector(self, arg0: Any) -> None: ...
    
    def ops(self) -> Any: ...
    
    def out(self) -> Any: ...
    
    # Multiple overloads for run
    def run(self) -> None: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any) -> Any: ...
    # def run(self, arg0: Any, arg1: Any) -> Any: ...
    
    def setEnvironment(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: Any) -> None: ...
    
    def setOutput(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...