"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class AbstractBigViewer:
    """
    AbstractBigViewer - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class Annotation3D:
    """
    sc.fiji.snt.viewer.Annotation3D
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:00:52.545372
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def colorCode(self, arg0: str, arg1: str) -> None: ...
    
    def getBarycentre(self) -> SNTPoint: ...
    
    def getColor(self) -> Any: ...
    
    def getDrawable(self) -> Any: ...
    
    def getLabel(self) -> str: ...
    
    def getType(self) -> str: ...
    
    def getVolume(self) -> float: ...
    
    def isColorCodeAllowed(self) -> bool: ...
    
    def meshToDrawable(self, arg0: Any) -> Any: ...
    
    def setBoundingBoxColor(self, arg0: Any) -> None: ...
    
    # Multiple overloads for setColor
    def setColor(self, arg0: Any, arg1: float) -> None: ...
    # def setColor(self, arg0: str) -> None: ...
    # def setColor(self, arg0: str, arg1: float) -> None: ...
    
    def setSize(self, arg0: Union[int, float]) -> None: ...
    
    def setTransparency(self, arg0: float) -> None: ...
    
    # Multiple overloads for setWireframeColor
    def setWireframeColor(self, arg0: Any) -> None: ...
    # def setWireframeColor(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Bdv:
    """
    Bdv - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class Bvv:
    """
    Bvv - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class BvvMultiSource:
    """
    sc.fiji.snt.viewer.BvvMultiSource
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:00:54.555498
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def applyTransform(self, arg0: Any) -> None: ...
    
    def getFollowers(self) -> List[Any]: ...
    
    def getLeader(self) -> Any: ...
    
    def getLeaderTransform(self, arg0: Any) -> None: ...
    
    def getSources(self) -> List[Any]: ...
    
    def isLiveSync(self) -> bool: ...
    
    def removeFromBvv(self) -> None: ...
    
    def setActive(self, arg0: bool) -> None: ...
    
    def setColor(self, arg0: Any) -> None: ...
    
    def setDisplayRange(self, arg0: float, arg1: float) -> None: ...
    
    def setLiveSync(self, arg0: bool) -> None: ...
    
    def size(self) -> int: ...
    
    def syncTransforms(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class BvvUtils:
    """
    sc.fiji.snt.viewer.BvvUtils
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:00:54.679057
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def preferMultiResolutionIfSafe(self, arg0: Any, arg1: int) -> None: ...
    
    def prefetchForShow(self, arg0: Any, arg1: int) -> None: ...
    
    def synthesizeMipmapPyramid(self, arg0: Any, arg1: int) -> Any: ...
    
    def warnIfLikelyRemoteImgPlus(self, arg0: Any, arg1: str) -> None: ...
    
    def warnIfLikelySimpleStack(self, arg0: Any, arg1: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MultiViewer2D:
    """
    sc.fiji.snt.viewer.MultiViewer2D
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:01.703045
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def save(self, arg0: str) -> None: ...
    
    def setAxesVisible(self, arg0: bool) -> None: ...
    
    # Multiple overloads for setColorBarLegend
    def setColorBarLegend(self, arg0: Any) -> None: ...
    # def setColorBarLegend(self, arg0: Any, arg1: float, arg2: float, arg3: int) -> None: ...
    # def setColorBarLegend(self, arg0: str, arg1: float, arg2: float) -> None: ...
    
    def setGridlinesVisible(self, arg0: bool) -> None: ...
    
    def setLabel(self, arg0: str) -> None: ...
    
    def setLayoutColumns(self, arg0: int) -> None: ...
    
    def setOutlineVisible(self, arg0: bool) -> None: ...
    
    def setTitle(self, arg0: str) -> None: ...
    
    def setXrange(self, arg0: float, arg1: float) -> None: ...
    
    def setYrange(self, arg0: float, arg1: float) -> None: ...
    
    def show(self) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MultiViewer3D:
    """
    sc.fiji.snt.viewer.MultiViewer3D
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:01.869762
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addColorBarLegend(self, arg0: Any) -> None: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setAnimationEnabled(self, arg0: bool) -> None: ...
    
    def setGap(self, arg0: int) -> None: ...
    
    def setLabels(self, arg0: List[Any]) -> None: ...
    
    def setLayoutColumns(self, arg0: int) -> None: ...
    
    def setTitle(self, arg0: str) -> None: ...
    
    def setViewMode(self, arg0: Any) -> None: ...
    
    def show(self) -> Any: ...
    
    def viewers(self) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class OBJMesh:
    """
    sc.fiji.snt.viewer.OBJMesh
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:02.734106
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def computePrincipalAxes(self, arg0: str) -> Any: ...
    
    def duplicate(self) -> Any: ...
    
    def getAngleWithLocalDirection(self, arg0: SNTPoint, arg1: Any, arg2: str, arg3: int) -> float: ...
    
    def getBoundingBox(self, arg0: str) -> BoundingBox: ...
    
    def getCentroid(self, arg0: str) -> SNTPoint: ...
    
    def getDisplayedHemisphere(self) -> str: ...
    
    def getDrawable(self) -> Any: ...
    
    def getLabel(self) -> str: ...
    
    def getLocalDirection(self, arg0: SNTPoint, arg1: str, arg2: int) -> Any: ...
    
    def getObj(self) -> Any: ...
    
    def getPrincipalAxes(self, arg0: str) -> Any: ...
    
    def getSourceAnnotation(self) -> Any: ...
    
    def getSymmetryAxis(self) -> int: ...
    
    # Multiple overloads for getVertices
    def getVertices(self) -> List[Any]: ...
    # def getVertices(self, arg0: str) -> List[Any]: ...
    
    def getVolume(self) -> float: ...
    
    def label(self) -> str: ...
    
    # Multiple overloads for setBoundingBoxColor
    def setBoundingBoxColor(self, arg0: str) -> None: ...
    # def setBoundingBoxColor(self, arg0: Any) -> None: ...
    
    # Multiple overloads for setColor
    def setColor(self, arg0: Any, arg1: float) -> None: ...
    # def setColor(self, arg0: str, arg1: float) -> None: ...
    
    def setDisplayedHemisphere(self, arg0: str) -> None: ...
    
    def setLabel(self, arg0: str) -> None: ...
    
    def setSourceAnnotation(self, arg0: Any) -> None: ...
    
    def setSymmetryAxis(self, arg0: int) -> None: ...
    
    def setTransparency(self, arg0: float) -> None: ...
    
    def setVolume(self, arg0: float) -> None: ...
    
    def translate(self, arg0: SNTPoint) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Viewer2D:
    """
    sc.fiji.snt.viewer.Viewer2D
    
    Generated from cached signatures.
    Extracted: 2026-09-27T23:01:12.923538
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for add
    def add(self, arg0: Tree, arg1: str) -> None: ...
    # def add(self, arg0: Tree, arg1: Any) -> None: ...
    # def add(self, arg0: List[Any], arg1: str) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    # def add(self, arg0: Tree, arg1: str, arg2: Any, arg3: float, arg4: float) -> None: ...
    # def add(self, arg0: Tree, arg1: str, arg2: str) -> None: ...
    # def add(self, arg0: Tree, arg1: str, arg2: str, arg3: float, arg4: float) -> None: ...
    
    # Multiple overloads for addColorBarLegend
    def addColorBarLegend(self, arg0: Any) -> None: ...
    # def addColorBarLegend(self, arg0: Any, arg1: float, arg2: float) -> None: ...
    # def addColorBarLegend(self) -> None: ...
    
    # Multiple overloads for addNodes
    def addNodes(self, arg0: Dict[str, Any]) -> None: ...
    # def addNodes(self, arg0: List[Any], arg1: str, arg2: str) -> None: ...
    
    def addPolygon(self, arg0: Any, arg1: str) -> None: ...
    
    def addTree(self, arg0: Tree) -> None: ...
    
    def addTrees(self, arg0: List[Any]) -> None: ...
    
    def getAvailableLuts(self) -> Set[Any]: ...
    
    def getChart(self) -> SNTChart: ...
    
    def getColor(self, arg0: float) -> Any: ...
    
    def getColorRGB(self, arg0: float) -> Any: ...
    
    # Multiple overloads for getColorTable
    def getColorTable(self, arg0: str) -> Any: ...
    # def getColorTable(self) -> Any: ...
    
    def getJFreeChart(self) -> Any: ...
    
    def getMetrics(self) -> List[Any]: ...
    
    def getMinMax(self) -> Any: ...
    
    def getMultiViewer(self) -> MultiViewer2D: ...
    
    def getNaNColor(self) -> Any: ...
    
    def getPlot(self) -> Any: ...
    
    def getTitle(self) -> str: ...
    
    def isIntegerScale(self) -> bool: ...
    
    def isNodeMapping(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    # Multiple overloads for map
    def map(self, arg0: Tree, arg1: Profile, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: Any, arg2: Any) -> None: ...
    # def map(self, arg0: Tree, arg1: str, arg2: str) -> None: ...
    # def map(self, arg0: Tree, arg1: str, arg2: Any) -> None: ...
    # def map(self, arg0: List[Any], arg1: str, arg2: str) -> None: ...
    # def map(self, arg0: str, arg1: Any) -> None: ...
    
    def mapTrees(self, arg0: List[Any], arg1: str) -> None: ...
    
    def setAxesVisible(self, arg0: bool) -> None: ...
    
    def setDefaultColor(self, arg0: Any) -> None: ...
    
    def setEqualizeAxes(self, arg0: bool) -> None: ...
    
    def setGridlinesVisible(self, arg0: bool) -> None: ...
    
    def setMinMax(self, arg0: float, arg1: float) -> None: ...
    
    def setNaNColor(self, arg0: Any) -> None: ...
    
    def setOutlineVisible(self, arg0: bool) -> None: ...
    
    def setPreferredSize(self, arg0: int, arg1: int) -> None: ...
    
    def setTitle(self, arg0: str) -> None: ...
    
    def setXrange(self, arg0: float, arg1: float) -> None: ...
    
    def setYrange(self, arg0: float, arg1: float) -> None: ...
    
    def show(self, arg0: int, arg1: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Viewer3D:
    """
    sc.fiji.snt.viewer.Viewer3D
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:36:45.083274
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for add
    def add(self, arg0: Any, arg1: str) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addColorBarLegend
    def addColorBarLegend(self, arg0: Any) -> None: ...
    # def addColorBarLegend(self, arg0: Any, arg1: float, arg2: float) -> None: ...
    # def addColorBarLegend(self, arg0: Any, arg1: float, arg2: float, arg3: bool) -> None: ...
    # def addColorBarLegend(self, arg0: Any, arg1: float, arg2: float, arg3: Any, arg4: int, arg5: int) -> None: ...
    
    def addLabel(self, arg0: str) -> None: ...
    
    def addMesh(self, arg0: Any) -> bool: ...
    
    def addTree(self, arg0: Tree) -> None: ...
    
    # Multiple overloads for addTrees
    def addTrees(self, arg0: List[Any], arg1: str, arg2: Any) -> None: ...
    # def addTrees(self, arg0: List[Any], arg1: str, arg2: float) -> None: ...
    # def addTrees(self, arg0: List[Any], arg1: bool) -> None: ...
    # def addTrees(self, arg0: List[Any], arg1: str) -> None: ...
    
    def annotateLine(self, arg0: List[Any], arg1: str) -> Any: ...
    
    def annotateMidPlane(self, arg0: BoundingBox, arg1: int, arg2: str) -> Any: ...
    
    def annotatePlane(self, arg0: SNTPoint, arg1: SNTPoint, arg2: str) -> Any: ...
    
    # Multiple overloads for annotatePoint
    def annotatePoint(self, arg0: SNTPoint, arg1: str) -> Any: ...
    # def annotatePoint(self, arg0: SNTPoint, arg1: str, arg2: str, arg3: float) -> Any: ...
    
    def annotatePoints(self, arg0: List[Any], arg1: str) -> Any: ...
    
    # Multiple overloads for annotateSurface
    def annotateSurface(self, arg0: List[Any], arg1: str, arg2: bool) -> Any: ...
    # def annotateSurface(self, arg0: List[Any], arg1: str) -> Any: ...
    
    def assignUniqueColors(self, arg0: List[Any]) -> None: ...
    
    # Multiple overloads for colorCode
    def colorCode(self, arg0: List[Any], arg1: str, arg2: Any) -> Any: ...
    # def colorCode(self, arg0: str, arg1: str, arg2: Any) -> Any: ...
    
    def dispose(self) -> None: ...
    
    def duplicate(self) -> Viewer3D: ...
    
    def freeze(self) -> None: ...
    
    def getAnnotation(self, arg0: str) -> Any: ...
    
    def getAnnotations(self) -> List[Any]: ...
    
    # Multiple overloads for getFrame
    def getFrame(self) -> Any: ...
    # def getFrame(self, arg0: bool) -> Any: ...
    
    def getID(self) -> int: ...
    
    def getManagerPanel(self) -> Any: ...
    
    def getMesh(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getMeshes
    def getMeshes(self) -> List[Any]: ...
    # def getMeshes(self, arg0: bool) -> List[Any]: ...
    
    def getRecorder(self, arg0: bool) -> Any: ...
    
    def getTree(self, arg0: str) -> Tree: ...
    
    # Multiple overloads for getTrees
    def getTrees(self) -> List[Any]: ...
    # def getTrees(self, arg0: bool) -> List[Any]: ...
    
    def isActive(self) -> bool: ...
    
    def isDarkModeOn(self) -> bool: ...
    
    def isSNTInstance(self) -> bool: ...
    
    def isSplitDendritesFromAxons(self) -> bool: ...
    
    def loadMesh(self, arg0: str, arg1: Any, arg2: float) -> Any: ...
    
    def loadRefBrain(self, arg0: str) -> Any: ...
    
    def logSceneControls(self) -> None: ...
    
    def mergeAnnotations(self, arg0: List[Any], arg1: str) -> Any: ...
    
    def rebuild(self, arg0: Any) -> None: ...
    
    def recordRotation(self, arg0: float, arg1: int, arg2: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Callable: ...
class Dict: ...
class List: ...