"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class FlyCircuitLoader:
    """
    sc.fiji.snt.io.FlyCircuitLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.224710
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getReader(self, arg0: str) -> Any: ...
    
    def getReconstructionURL(self, arg0: str) -> str: ...
    
    def getTree(self, arg0: str) -> Tree: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class InsectBrainLoader:
    """
    sc.fiji.snt.io.InsectBrainLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.249878
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAnnotations(self) -> List[Any]: ...
    
    def getMeshes(self) -> List[Any]: ...
    
    def getNeuronInfo(self) -> Any: ...
    
    def getTree(self) -> Tree: ...
    
    def idExists(self) -> bool: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MouseLightLoader:
    """
    sc.fiji.snt.io.MouseLightLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.301662
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def demoTrees(self) -> List[Any]: ...
    
    # Multiple overloads for extractNodes
    def extractNodes(self, arg0: str, arg1: str) -> Dict[str, Any]: ...
    # def extractNodes(self, arg0: Any, arg1: str) -> Dict[str, Any]: ...
    
    # Multiple overloads for extractTrees
    def extractTrees(self, arg0: str, arg1: str) -> Dict[str, Any]: ...
    # def extractTrees(self, arg0: Any, arg1: str) -> Dict[str, Any]: ...
    
    def getAllLoaders(self) -> List[Any]: ...
    
    def getDOI(self) -> str: ...
    
    def getID(self) -> str: ...
    
    def getJSON(self) -> Any: ...
    
    def getNeuronCount(self) -> int: ...
    
    # Multiple overloads for getNodes
    def getNodes(self) -> Set[Any]: ...
    # def getNodes(self, arg0: str) -> Set[Any]: ...
    
    def getSWC(self) -> str: ...
    
    def getSampleInfo(self) -> str: ...
    
    def getSomaCompartment(self) -> Any: ...
    
    def getSomaLocation(self) -> SWCPoint: ...
    
    # Multiple overloads for getTree
    def getTree(self) -> Tree: ...
    # def getTree(self, arg0: str) -> Tree: ...
    # def getTree(self, arg0: str, arg1: Any) -> Tree: ...
    
    def idExists(self) -> bool: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    # Multiple overloads for save
    def save(self, arg0: str) -> bool: ...
    # def save(self, arg0: str) -> bool: ...
    
    def saveAsJSON(self, arg0: str) -> bool: ...
    
    def saveAsSWC(self, arg0: str) -> bool: ...
    
    def __getattr__(self, name: str) -> Any: ...


class MouseLightQuerier:
    """
    sc.fiji.snt.io.MouseLightQuerier
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.304334
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAllIDs(self) -> List[Any]: ...
    
    # Multiple overloads for getIDs
    def getIDs(self, arg0: Any) -> List[Any]: ...
    # def getIDs(self, arg0: List[Any]) -> List[Any]: ...
    # def getIDs(self, arg0: List[Any], arg1: bool) -> List[Any]: ...
    # def getIDs(self, arg0: str, arg1: bool) -> List[Any]: ...
    
    def getNeuronCount(self) -> int: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def setCCFVersion(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class NeuroMorphoLoader:
    """
    sc.fiji.snt.io.NeuroMorphoLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.346631
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def enableSourceVersion(self, arg0: bool) -> None: ...
    
    def get(self, arg0: str) -> Tree: ...
    
    def getReader(self, arg0: str) -> Any: ...
    
    def getReconstructionURL(self, arg0: str) -> str: ...
    
    def getTree(self, arg0: str) -> Tree: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class RemoteSWCLoader:
    """
    sc.fiji.snt.io.RemoteSWCLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.484923
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def download(self, arg0: str, arg1: str) -> bool: ...
    
    def getReader(self, arg0: str) -> Any: ...
    
    def getReconstructionURL(self, arg0: str) -> str: ...
    
    def getTree(self, arg0: str) -> Tree: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def __getattr__(self, name: str) -> Any: ...


class WekaModelLoader:
    """
    sc.fiji.snt.io.WekaModelLoader
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.793288
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for addInput
    def addInput(self, arg0: str, arg1: type) -> Any: ...
    # def addInput(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addOutput
    def addOutput(self, arg0: Any) -> None: ...
    # def addOutput(self, arg0: str, arg1: type) -> Any: ...
    
    # Multiple overloads for cancel
    def cancel(self, arg0: str) -> None: ...
    # def cancel(self) -> None: ...
    
    def context(self) -> Any: ...
    
    def getCancelReason(self) -> str: ...
    
    def getContext(self) -> Any: ...
    
    def getDelegateObject(self) -> Any: ...
    
    # Multiple overloads for getInfo
    def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    # def getInfo(self) -> Any: ...
    
    def getInput(self, arg0: str) -> Any: ...
    
    def getInputs(self) -> Dict[str, Any]: ...
    
    def getOutput(self, arg0: str) -> Any: ...
    
    def getOutputs(self) -> Dict[str, Any]: ...
    
    def initialize(self) -> None: ...
    
    def isCanceled(self) -> bool: ...
    
    def isInputResolved(self, arg0: str) -> bool: ...
    
    def isOutputResolved(self, arg0: str) -> bool: ...
    
    def isResolved(self, arg0: str) -> bool: ...
    
    def preview(self) -> None: ...
    
    def removeInput(self, arg0: Any) -> None: ...
    
    def removeOutput(self, arg0: Any) -> None: ...
    
    def resolveInput(self, arg0: str) -> None: ...
    
    def resolveOutput(self, arg0: str) -> None: ...
    
    def run(self) -> None: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setInput(self, arg0: str, arg1: Any) -> None: ...
    
    def setInputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setOutput(self, arg0: str, arg1: Any) -> None: ...
    
    def setOutputs(self, arg0: Dict[str, Any]) -> None: ...
    
    def setResolved(self, arg0: str, arg1: bool) -> None: ...
    
    def uncancel(self) -> None: ...
    
    def unresolveInput(self, arg0: str) -> None: ...
    
    def unresolveOutput(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Constants imported from converters.core
LAYOUT_BIOFORMATS2RAW: Any
LAYOUT_OME_NGFF: Any
LAYOUT_UNKNOWN: Any

# Imported functions
def detect_zarr_layout(*args: Any, **kwargs: Any) -> Any: ...
def get_available_levels() -> Any: ...
def get_dataset_path() -> Any: ...
def get_dataset_path_from_metadata() -> Any: ...
def get_zattrs_path() -> Any: ...
def imgplus_from_zarr(*args: Any, **kwargs: Any) -> Any: ...
def inspect_zarr(*args: Any, **kwargs: Any) -> Any: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...