"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable

class ArraySearchImage:
    """
    SNT ArraySearchImage class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any, arg1: int, arg2: int) -> None: ...

    # Methods
    def forEach(self, arg0: Any) -> None: ...
    def getValue(self, arg0: int, arg1: int) -> Any: ...
    def iterator(self) -> Any: ...
    def setValue(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    def spliterator(self) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class ListSearchImage:
    """
    SNT ListSearchImage class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any, arg1: int, arg2: int) -> None: ...

    # Methods
    def forEach(self, arg0: Any) -> None: ...
    def getValue(self, arg0: int, arg1: int) -> Any: ...
    def iterator(self) -> Any: ...
    def setValue(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    def spliterator(self) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class MapSearchImage:
    """
    SNT MapSearchImage class with complete method signatures.
    Generated using Java reflection.
    """

    def __init__(self) -> None:
        """Initialize MapSearchImage."""
        ...

    # Methods
    def forEach(self, arg0: Any) -> None: ...
    def getValue(self, arg0: int, arg1: int) -> Any: ...
    def iterator(self) -> Any: ...
    def setValue(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    def spliterator(self) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class SearchImageStack:
    """
    SNT SearchImageStack class with complete method signatures.
    Generated using Java reflection.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any) -> None: ...

    # Methods
    def forEach(self, arg0: Any) -> None: ...
    def getSlice(self, arg0: int) -> Any: ...
    def iterator(self) -> Any: ...
    def keySet(self) -> Set[Any]: ...
    def newSlice(self, arg0: int) -> Any: ...
    def size(self) -> int: ...
    def spliterator(self) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...

class SupplierUtil:
    """
    SNT SupplierUtil class with complete method signatures.
    Generated using Java reflection.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize SupplierUtil."""
        ...

    # Methods
    @staticmethod
    def createSupplier(arg0: Any, arg1: Any, arg2: int, arg3: int) -> Any: ...

    def __getattr__(self, name: str) -> Any:
        """Dynamic attribute access for additional methods."""
        ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """Make the class callable."""
        ...


# Other functions
def get_available_classes() -> Any: ...
def get_class(class_name: str) -> Any: ...
def get_curated_classes() -> Any: ...
def get_extended_classes() -> Any: ...
def list_classes() -> None: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...

# Constants
CURATED_CLASSES: List[str]
EXTENDED_CLASSES: List[str]