"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class Fill:
    """
    sc.fiji.snt.Fill
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.261958
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def add(self, arg0: int, arg1: int, arg2: int, arg3: float, arg4: int, arg5: bool) -> None: ...
    
    def getEstimatedMeanRadius(self) -> float: ...
    
    def getMetric(self) -> Any: ...
    
    def getNodeList(self) -> List[Any]: ...
    
    def getSourcePaths(self) -> Set[Any]: ...
    
    def getSourcePathsStringHuman(self) -> str: ...
    
    def getSourcePathsStringMachine(self) -> str: ...
    
    def getThreshold(self) -> float: ...
    
    def getVolume(self) -> float: ...
    
    def setMetric(self, arg0: Any) -> None: ...
    
    # Multiple overloads for setSourcePaths
    def setSourcePaths(self, arg0: Any) -> None: ...
    # def setSourcePaths(self, arg0: Set[Any]) -> None: ...
    
    def setSpacing(self, arg0: float, arg1: float, arg2: float, arg3: str) -> None: ...
    
    def setThreshold(self, arg0: float) -> None: ...
    
    def writeNodesXML(self, arg0: Any) -> None: ...
    
    def writeXML(self, arg0: Any, arg1: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class FillConverter:
    """
    sc.fiji.snt.FillConverter
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.264368
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def convert(self, arg0: Any, arg1: Any) -> None: ...
    
    def convertBinary(self, arg0: Any) -> None: ...
    
    def convertDistance(self, arg0: Any) -> None: ...
    
    def convertLabels(self, arg0: Any) -> None: ...
    
    def getFillerStack(self) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class InteractiveTracerCanvas:
    """
    sc.fiji.snt.InteractiveTracerCanvas
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.324407
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    def add(self, arg0: Any) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: Any) -> bool: ...
    # def contains(self, arg0: int, arg1: int) -> bool: ...
    
    # Multiple overloads for createBufferStrategy
    def createBufferStrategy(self, arg0: int, arg1: Any) -> None: ...
    # def createBufferStrategy(self, arg0: int) -> None: ...
    
    # Multiple overloads for createImage
    def createImage(self, arg0: Any) -> Any: ...
    # def createImage(self, arg0: int, arg1: int) -> Any: ...
    
    # Multiple overloads for createVolatileImage
    def createVolatileImage(self, arg0: int, arg1: int, arg2: Any) -> Any: ...
    # def createVolatileImage(self, arg0: int, arg1: int) -> Any: ...
    
    def cursorOverImage(self) -> bool: ...
    
    def deliverEvent(self, arg0: Any) -> None: ...
    
    def disable(self) -> None: ...
    
    def disableEvents(self, arg0: bool) -> None: ...
    
    def disablePopupMenu(self, arg0: bool) -> None: ...
    
    def dispatchEvent(self, arg0: Any) -> None: ...
    
    def doLayout(self) -> None: ...
    
    # Multiple overloads for enable
    def enable(self, arg0: bool) -> None: ...
    # def enable(self) -> None: ...
    
    # Multiple overloads for firePropertyChange
    def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: str, arg2: str) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: float, arg2: float) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: float, arg2: float) -> None: ...
    
    def fitToWindow(self) -> None: ...
    
    def getAccessibleContext(self) -> Any: ...
    
    def getAlignmentX(self) -> float: ...
    
    def getAlignmentY(self) -> float: ...
    
    def getAnnotationsColor(self) -> Any: ...
    
    def getBackground(self) -> Any: ...
    
    def getBaseline(self, arg0: int, arg1: int) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Path:
    """
    sc.fiji.snt.Path
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.394817
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def add(self, arg0: Any) -> None: ...
    
    def addAsLinesTo3DViewer(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    
    # Multiple overloads for addDiscsTo3DViewer
    def addDiscsTo3DViewer(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    # def addDiscsTo3DViewer(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    
    def addNode(self, arg0: Any) -> None: ...
    
    def addPointDouble(self, arg0: float, arg1: float, arg2: float) -> None: ...
    
    # Multiple overloads for addTo3DViewer
    def addTo3DViewer(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...
    # def addTo3DViewer(self, arg0: Any, arg1: Any, arg2: Any) -> None: ...
    
    # Multiple overloads for clone
    def clone(self) -> Any: ...
    # def clone(self) -> Any: ...
    # def clone(self, arg0: bool) -> Any: ...
    
    # Multiple overloads for compareTo
    def compareTo(self, arg0: Any) -> int: ...
    # def compareTo(self, arg0: Any) -> int: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: Any) -> bool: ...
    # def contains(self, arg0: Any, arg1: float) -> bool: ...
    
    def createCircles(self) -> None: ...
    
    def createPath(self) -> Any: ...
    
    def detachFromParent(self) -> None: ...
    
    def downsample(self, arg0: float) -> None: ...
    
    # Multiple overloads for drawPathAsPoints
    def drawPathAsPoints(self, arg0: Any, arg1: Any, arg2: Any, arg3: int, arg4: bool, arg5: bool) -> None: ...
    # def drawPathAsPoints(self, arg0: Any, arg1: Any, arg2: Any, arg3: bool, arg4: bool, arg5: int, arg6: int) -> None: ...
    
    def findJunctionIndices(self) -> Any: ...
    
    def findJunctions(self) -> List[Any]: ...
    
    def firstNode(self) -> Any: ...
    
    def getAngle(self, arg0: int) -> float: ...
    
    def getApproximatedSurface(self) -> float: ...
    
    def getApproximatedVolume(self) -> float: ...
    
    def getBranchPoint(self) -> Any: ...
    
    def getBranchPointIndex(self) -> int: ...
    
    def getBranchPoints(self) -> Set[Any]: ...
    
    def getCalibration(self) -> Any: ...
    
    def getCanvasOffset(self) -> Any: ...
    
    def getChannel(self) -> int: ...
    
    def getChildren(self) -> List[Any]: ...
    
    def getColor(self) -> Any: ...
    
    def getColorRGB(self) -> Any: ...
    
    def getContraction(self) -> float: ...
    
    def getEditableNodeIndex(self) -> int: ...
    
    # Multiple overloads for getExtensionAngle3D
    def getExtensionAngle3D(self, arg0: Any) -> float: ...
    # def getExtensionAngle3D(self, arg0: bool) -> float: ...
    
    def getExtensionAngleFromHorizontal(self) -> float: ...
    
    def getExtensionAngleFromVertical(self) -> float: ...
    
    def getExtensionAngleXY(self) -> float: ...
    
    def getExtensionAngleXZ(self) -> float: ...
    
    def getExtensionAngleZY(self) -> float: ...
    
    def getExtensionAngles3D(self) -> Any: ...
    
    def getExtensionDirection3D(self) -> Any: ...
    
    def getFitted(self) -> Any: ...
    
    def getFractalDimension(self) -> float: ...
    
    def getFrame(self) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathAndFillManager:
    """
    sc.fiji.snt.PathAndFillManager
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.406995
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for addPath
    def addPath(self, arg0: Any) -> None: ...
    # def addPath(self, arg0: Any, arg1: int, arg2: int) -> None: ...
    # def addPath(self, arg0: Any, arg1: bool, arg2: bool) -> None: ...
    
    def addPathAndFillListener(self, arg0: Any) -> None: ...
    
    # Multiple overloads for addTree
    def addTree(self, arg0: Any) -> None: ...
    # def addTree(self, arg0: Any, arg1: str) -> None: ...
    
    def addTrees(self, arg0: List[Any]) -> None: ...
    
    def allPointsIterator(self) -> Any: ...
    
    def anySelected(self) -> bool: ...
    
    def assignSpatialSettings(self, arg0: Any) -> None: ...
    
    def canvasResized(self) -> None: ...
    
    def characters(self, arg0: Any, arg1: int, arg2: int) -> None: ...
    
    def clear(self) -> None: ...
    
    def contentAdded(self, arg0: Any) -> None: ...
    
    def contentChanged(self, arg0: Any) -> None: ...
    
    def contentRemoved(self, arg0: Any) -> None: ...
    
    def contentSelected(self, arg0: Any) -> None: ...
    
    def createFromFile(self, arg0: str, arg1: Any) -> Any: ...
    
    def createFromGraph(self, arg0: Any, arg1: bool) -> Any: ...
    
    def createFromNodes(self, arg0: List[Any]) -> Any: ...
    
    def declaration(self, arg0: str, arg1: str, arg2: str) -> None: ...
    
    # Multiple overloads for deletePath
    def deletePath(self, arg0: int) -> bool: ...
    # def deletePath(self, arg0: Any) -> bool: ...
    
    # Multiple overloads for deletePaths
    def deletePaths(self, arg0: List[Any]) -> bool: ...
    # def deletePaths(self, arg0: Any) -> None: ...
    
    def dispose(self) -> None: ...
    
    def downsampleAll(self, arg0: float) -> None: ...
    
    def endDocument(self) -> None: ...
    
    def endElement(self, arg0: str, arg1: str, arg2: str) -> None: ...
    
    def endPrefixMapping(self, arg0: str) -> None: ...
    
    def error(self, arg0: Any) -> None: ...
    
    def exportAllPathsAsSWC(self, arg0: str) -> bool: ...
    
    def exportFillsAsCSV(self, arg0: Any) -> None: ...
    
    def exportToCSV(self, arg0: Any) -> None: ...
    
    def exportTree(self, arg0: int, arg1: Any) -> bool: ...
    
    def fatalError(self, arg0: Any) -> None: ...
    
    def getBoundingBox(self, arg0: bool) -> Any: ...
    
    def getCorrespondences(self, arg0: Any, arg1: float) -> List[Any]: ...
    
    def getLoadedFills(self) -> Dict[str, Any]: ...
    
    def getPath(self, arg0: int) -> Any: ...
    
    def getPathFromID(self, arg0: int) -> Any: ...
    
    def getPathFromName(self, arg0: str, arg1: bool) -> Any: ...
    
    def getPaths(self) -> List[Any]: ...
    
    def getPathsFiltered(self) -> List[Any]: ...
    
    def getPathsInROI(self, arg0: Any) -> List[Any]: ...
    
    # Multiple overloads for getPathsStructured
    def getPathsStructured(self, arg0: List[Any]) -> Any: ...
    # def getPathsStructured(self) -> Any: ...
    
    def getPlugin(self) -> Any: ...
    
    def getSWCFor(self, arg0: List[Any]) -> List[Any]: ...
    
    def getSelectedPaths(self) -> Set[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathChangeListener:
    """
    sc.fiji.snt.PathChangeListener
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.408096
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def pathChanged(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathDownsampler:
    """
    sc.fiji.snt.PathDownsampler
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.409533
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathFitter:
    """
    sc.fiji.snt.PathFitter
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.417312
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def applySettings(self, arg0: Any) -> None: ...
    
    # Multiple overloads for call
    def call(self) -> Any: ...
    # def call(self) -> Any: ...
    
    def getMaxRadius(self) -> int: ...
    
    def getPath(self) -> Any: ...
    
    def getSucceeded(self) -> bool: ...
    
    def readPreferences(self) -> None: ...
    
    def setImage(self, arg0: Any) -> None: ...
    
    def setMaxRadius(self, arg0: int) -> None: ...
    
    def setProgressCallback(self, arg0: int, arg1: Any) -> None: ...
    
    def setRadiusFallback(self, arg0: int) -> None: ...
    
    def setReplaceNodes(self, arg0: bool) -> None: ...
    
    def setScope(self, arg0: int) -> None: ...
    
    def setShowAnnotatedView(self, arg0: bool) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathManagerUI:
    """
    sc.fiji.snt.PathManagerUI
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.455041
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    # Multiple overloads for add
    def add(self, arg0: str, arg1: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: int) -> Any: ...
    # def add(self, arg0: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: Any) -> None: ...
    # def add(self, arg0: Any, arg1: Any, arg2: int) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addContainerListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    
    def addWindowFocusListener(self, arg0: Any) -> None: ...
    
    def addWindowListener(self, arg0: Any) -> None: ...
    
    def addWindowStateListener(self, arg0: Any) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    def applyDefaultTags(self, arg0: Any) -> None: ...
    
    # Multiple overloads for applyResourceBundle
    def applyResourceBundle(self, arg0: str) -> None: ...
    # def applyResourceBundle(self, arg0: Any) -> None: ...
    
    # Multiple overloads for applySelectionFilter
    def applySelectionFilter(self, arg0: str) -> None: ...
    # def applySelectionFilter(self, arg0: str, arg1: Any) -> None: ...
    # def applySelectionFilter(self, arg0: str, arg1: Any, arg2: Any) -> None: ...
    
    def applyTag(self, arg0: str) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    def clearSelection(self) -> None: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: Any) -> bool: ...
    # def contains(self, arg0: int, arg1: int) -> bool: ...
    
    def countComponents(self) -> int: ...
    
    # Multiple overloads for createBufferStrategy
    def createBufferStrategy(self, arg0: int) -> None: ...
    # def createBufferStrategy(self, arg0: int, arg1: Any) -> None: ...
    
    # Multiple overloads for createImage
    def createImage(self, arg0: Any) -> Any: ...
    # def createImage(self, arg0: int, arg1: int) -> Any: ...
    
    # Multiple overloads for createVolatileImage
    def createVolatileImage(self, arg0: int, arg1: int, arg2: Any) -> Any: ...
    # def createVolatileImage(self, arg0: int, arg1: int) -> Any: ...
    
    def deliverEvent(self, arg0: Any) -> None: ...
    
    def disable(self) -> None: ...
    
    def dispatchEvent(self, arg0: Any) -> None: ...
    
    def dispose(self) -> None: ...
    
    def doLayout(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SciViewSNT:
    """
    sc.fiji.snt.SciViewSNT
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.737033
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addTree(self, arg0: Any) -> None: ...
    
    def getSciView(self) -> Any: ...
    
    def getTreeAsSceneryNode(self, arg0: Any) -> Any: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def removeTree(self, arg0: Any) -> bool: ...
    
    def setSciView(self, arg0: Any) -> None: ...
    
    def syncPathManagerList(self) -> bool: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNT:
    """
    sc.fiji.snt.SNT
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.484414
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def accessToValidImageData(self) -> bool: ...
    
    def addFillerThread(self, arg0: Any) -> None: ...
    
    def addListener(self, arg0: Any) -> None: ...
    
    # Multiple overloads for autoTrace
    def autoTrace(self, arg0: List[Any], arg1: Any, arg2: bool) -> Any: ...
    # def autoTrace(self, arg0: Any, arg1: Any, arg2: Any, arg3: bool) -> Any: ...
    # def autoTrace(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    # def autoTrace(self, arg0: List[Any], arg1: Any) -> Any: ...
    
    def cancelPath(self) -> None: ...
    
    def cancelSearch(self, arg0: bool) -> None: ...
    
    def cancelTemporary(self) -> None: ...
    
    # Multiple overloads for captureView
    def captureView(self, arg0: str, arg1: bool) -> Any: ...
    # def captureView(self, arg0: str, arg1: Any) -> Any: ...
    
    def changeUIState(self, arg0: int) -> None: ...
    
    def closeAndResetAllPanes(self) -> None: ...
    
    def confirmTemporary(self, arg0: bool) -> None: ...
    
    # Multiple overloads for createCanvas
    def createCanvas(self, arg0: Any, arg1: int) -> Any: ...
    # def createCanvas(self, arg0: Any, arg1: int) -> Any: ...
    
    def disableEventsAllPanes(self, arg0: bool) -> None: ...
    
    def disableZoomAllPanes(self, arg0: bool) -> None: ...
    
    def editModeAllowed(self) -> bool: ...
    
    def enableAstar(self, arg0: bool) -> None: ...
    
    def enableAutoActivation(self, arg0: bool) -> None: ...
    
    def enableAutoSelectionOfFinishedPath(self, arg0: bool) -> None: ...
    
    def enableSecondaryLayerTracing(self, arg0: bool) -> None: ...
    
    def enableSnapCursor(self, arg0: bool) -> None: ...
    
    def findPointInStack(self, arg0: int, arg1: int, arg2: int, arg3: Any) -> None: ...
    
    def findPointInStackPrecise(self, arg0: float, arg1: float, arg2: int, arg3: Any) -> None: ...
    
    def finished(self, arg0: Any, arg1: bool) -> None: ...
    
    def flushSecondaryData(self) -> None: ...
    
    def getAverageSeparation(self) -> float: ...
    
    def getChannel(self) -> int: ...
    
    def getContext(self) -> Any: ...
    
    def getCostType(self) -> Any: ...
    
    def getCurrentPath(self) -> Any: ...
    
    def getDataset(self) -> Any: ...
    
    def getDepth(self) -> int: ...
    
    def getDrawDiameters(self) -> bool: ...
    
    def getFilledBinaryImp(self) -> Any: ...
    
    def getFilledDistanceImp(self) -> Any: ...
    
    def getFilledImp(self) -> Any: ...
    
    def getFilledLabelImp(self) -> Any: ...
    
    def getFilterType(self) -> Any: ...
    
    def getFrame(self) -> int: ...
    
    def getHeight(self) -> int: ...
    
    def getHeuristicType(self) -> Any: ...
    
    # Multiple overloads for getImagePlus
    def getImagePlus(self) -> Any: ...
    # def getImagePlus(self, arg0: int) -> Any: ...
    
    def getLoadedData(self) -> Any: ...
    
    def getLoadedDataAsImp(self) -> Any: ...
    
    def getLoadedIterable(self) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTService:
    """
    sc.fiji.snt.SNTService
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.665827
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def assignValues(self, arg0: bool) -> None: ...
    
    # Multiple overloads for compareTo
    def compareTo(self, arg0: Any) -> int: ...
    # def compareTo(self, arg0: Any) -> int: ...
    
    def context(self) -> Any: ...
    
    def demoImage(self, arg0: str) -> Any: ...
    
    # Multiple overloads for demoTree
    def demoTree(self) -> Any: ...
    # def demoTree(self, arg0: str) -> Any: ...
    
    def demoTreeImage(self) -> Any: ...
    
    def demoTrees(self) -> List[Any]: ...
    
    def dispose(self) -> None: ...
    
    def getAnalyzer(self, arg0: bool) -> Any: ...
    
    def getContext(self) -> Any: ...
    
    def getIdentifier(self) -> str: ...
    
    def getInfo(self) -> Any: ...
    
    def getInstance(self) -> Any: ...
    
    def getLocation(self) -> str: ...
    
    def getOrCreateSciViewSNT(self) -> Any: ...
    
    def getPathAndFillManager(self) -> Any: ...
    
    def getPaths(self) -> List[Any]: ...
    
    def getPlugin(self) -> Any: ...
    
    def getPriority(self) -> float: ...
    
    # Multiple overloads for getRecViewer
    def getRecViewer(self, arg0: int) -> Any: ...
    # def getRecViewer(self) -> Any: ...
    
    def getSciViewSNT(self) -> Any: ...
    
    def getSelectedPaths(self) -> List[Any]: ...
    
    def getStatistics(self, arg0: bool) -> Any: ...
    
    def getTable(self) -> Any: ...
    
    # Multiple overloads for getTree
    def getTree(self) -> Any: ...
    # def getTree(self, arg0: bool) -> Any: ...
    
    def getTrees(self) -> List[Any]: ...
    
    def getUI(self) -> Any: ...
    
    def getVersion(self) -> str: ...
    
    # Multiple overloads for initialize
    def initialize(self, arg0: Any, arg1: bool) -> Any: ...
    # def initialize(self, arg0: bool) -> Any: ...
    # def initialize(self, arg0: str, arg1: bool) -> Any: ...
    # def initialize(self) -> None: ...
    
    def isActive(self) -> bool: ...
    
    def loadGraph(self, arg0: Any) -> None: ...
    
    def loadTracings(self, arg0: str) -> None: ...
    
    def loadTree(self, arg0: Any) -> None: ...
    
    def log(self) -> Any: ...
    
    def newRecViewer(self, arg0: bool) -> Any: ...
    
    def registerEventHandlers(self) -> None: ...
    
    def save(self, arg0: str) -> bool: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setInfo(self, arg0: Any) -> None: ...
    
    def setPriority(self, arg0: float) -> None: ...
    
    def updateViewers(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTUI:
    """
    sc.fiji.snt.SNTUI
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.707790
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    # Multiple overloads for add
    def add(self, arg0: str, arg1: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: int) -> Any: ...
    # def add(self, arg0: Any) -> Any: ...
    # def add(self, arg0: Any, arg1: Any) -> None: ...
    # def add(self, arg0: Any, arg1: Any, arg2: int) -> None: ...
    # def add(self, arg0: Any) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addContainerListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    
    def addWindowFocusListener(self, arg0: Any) -> None: ...
    
    def addWindowListener(self, arg0: Any) -> None: ...
    
    def addWindowStateListener(self, arg0: Any) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    # Multiple overloads for applyResourceBundle
    def applyResourceBundle(self, arg0: str) -> None: ...
    # def applyResourceBundle(self, arg0: Any) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    def changeState(self, arg0: int) -> None: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: Any) -> bool: ...
    # def contains(self, arg0: int, arg1: int) -> bool: ...
    
    def countComponents(self) -> int: ...
    
    # Multiple overloads for createBufferStrategy
    def createBufferStrategy(self, arg0: int) -> None: ...
    # def createBufferStrategy(self, arg0: int, arg1: Any) -> None: ...
    
    # Multiple overloads for createImage
    def createImage(self, arg0: Any) -> Any: ...
    # def createImage(self, arg0: int, arg1: int) -> Any: ...
    
    # Multiple overloads for createVolatileImage
    def createVolatileImage(self, arg0: int, arg1: int, arg2: Any) -> Any: ...
    # def createVolatileImage(self, arg0: int, arg1: int) -> Any: ...
    
    def deliverEvent(self, arg0: Any) -> None: ...
    
    def disable(self) -> None: ...
    
    def dispatchEvent(self, arg0: Any) -> None: ...
    
    def dispose(self) -> None: ...
    
    def doLayout(self) -> None: ...
    
    # Multiple overloads for enable
    def enable(self, arg0: bool) -> None: ...
    # def enable(self) -> None: ...
    
    def error(self, arg0: str) -> None: ...
    
    def findComponentAt(self, arg0: Any) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTUtils:
    """
    sc.fiji.snt.SNTUtils
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.713971
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addViewer(self, arg0: Any) -> None: ...
    
    def buildDate(self) -> str: ...
    
    def csvQuoteAndPrint(self, arg0: Any, arg1: Any) -> None: ...
    
    def downloadToTempFile(self, arg0: str) -> Any: ...
    
    # Multiple overloads for error
    def error(self, arg0: str, arg1: Any) -> None: ...
    # def error(self, arg0: str) -> None: ...
    
    def extractReadableTimeStamp(self, arg0: Any) -> str: ...
    
    def fileAvailable(self, arg0: Any) -> bool: ...
    
    # Multiple overloads for findClosestPair
    def findClosestPair(self, arg0: Any, arg1: str) -> Any: ...
    # def findClosestPair(self, arg0: Any, arg1: Any) -> Any: ...
    
    def formatDouble(self, arg0: float, arg1: int) -> str: ...
    
    def getBackupCopies(self, arg0: Any) -> List[Any]: ...
    
    def getContext(self) -> Any: ...
    
    def getDecimalFormat(self, arg0: float, arg1: int) -> Any: ...
    
    def getElapsedTime(self, arg0: int) -> str: ...
    
    def getInstance(self) -> Any: ...
    
    def getPluginInstance(self) -> Any: ...
    
    def getReadableVersion(self) -> str: ...
    
    def getReconstructionFiles(self, arg0: Any, arg1: str) -> Any: ...
    
    def getSanitizedUnit(self, arg0: str) -> str: ...
    
    def getTimeStamp(self) -> str: ...
    
    # Multiple overloads for getUniquelySuffixedFile
    def getUniquelySuffixedFile(self, arg0: Any) -> Any: ...
    # def getUniquelySuffixedFile(self, arg0: Any, arg1: str) -> Any: ...
    
    def getUniquelySuffixedTifFile(self, arg0: Any) -> Any: ...
    
    def isContextSet(self) -> bool: ...
    
    def isDebugMode(self) -> bool: ...
    
    def isReconstructionFile(self, arg0: Any) -> bool: ...
    
    def log(self, arg0: str) -> None: ...
    
    def randomPaths(self) -> List[Any]: ...
    
    def removeViewer(self, arg0: Any) -> None: ...
    
    def setContext(self, arg0: Any) -> None: ...
    
    def setDebugMode(self, arg0: bool) -> None: ...
    
    def setIsLoading(self, arg0: bool) -> None: ...
    
    def startApp(self) -> Any: ...
    
    def stripExtension(self, arg0: str) -> str: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TracerCanvas:
    """
    sc.fiji.snt.TracerCanvas
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.779109
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def action(self, arg0: Any, arg1: Any) -> bool: ...
    
    def add(self, arg0: Any) -> None: ...
    
    def addComponentListener(self, arg0: Any) -> None: ...
    
    def addFocusListener(self, arg0: Any) -> None: ...
    
    def addHierarchyBoundsListener(self, arg0: Any) -> None: ...
    
    def addHierarchyListener(self, arg0: Any) -> None: ...
    
    def addInputMethodListener(self, arg0: Any) -> None: ...
    
    def addKeyListener(self, arg0: Any) -> None: ...
    
    def addMouseListener(self, arg0: Any) -> None: ...
    
    def addMouseMotionListener(self, arg0: Any) -> None: ...
    
    def addMouseWheelListener(self, arg0: Any) -> None: ...
    
    def addNotify(self) -> None: ...
    
    # Multiple overloads for addPropertyChangeListener
    def addPropertyChangeListener(self, arg0: Any) -> None: ...
    # def addPropertyChangeListener(self, arg0: str, arg1: Any) -> None: ...
    
    def applyComponentOrientation(self, arg0: Any) -> None: ...
    
    def areFocusTraversalKeysSet(self, arg0: int) -> bool: ...
    
    def bounds(self) -> Any: ...
    
    # Multiple overloads for checkImage
    def checkImage(self, arg0: Any, arg1: Any) -> int: ...
    # def checkImage(self, arg0: Any, arg1: int, arg2: int, arg3: Any) -> int: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: Any) -> bool: ...
    # def contains(self, arg0: int, arg1: int) -> bool: ...
    
    # Multiple overloads for createBufferStrategy
    def createBufferStrategy(self, arg0: int, arg1: Any) -> None: ...
    # def createBufferStrategy(self, arg0: int) -> None: ...
    
    # Multiple overloads for createImage
    def createImage(self, arg0: Any) -> Any: ...
    # def createImage(self, arg0: int, arg1: int) -> Any: ...
    
    # Multiple overloads for createVolatileImage
    def createVolatileImage(self, arg0: int, arg1: int, arg2: Any) -> Any: ...
    # def createVolatileImage(self, arg0: int, arg1: int) -> Any: ...
    
    def cursorOverImage(self) -> bool: ...
    
    def deliverEvent(self, arg0: Any) -> None: ...
    
    def disable(self) -> None: ...
    
    def disableEvents(self, arg0: bool) -> None: ...
    
    def disablePopupMenu(self, arg0: bool) -> None: ...
    
    def dispatchEvent(self, arg0: Any) -> None: ...
    
    def doLayout(self) -> None: ...
    
    # Multiple overloads for enable
    def enable(self, arg0: bool) -> None: ...
    # def enable(self) -> None: ...
    
    # Multiple overloads for firePropertyChange
    def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: str, arg2: str) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: float, arg2: float) -> None: ...
    # def firePropertyChange(self, arg0: str, arg1: float, arg2: float) -> None: ...
    
    def fitToWindow(self) -> None: ...
    
    def getAccessibleContext(self) -> Any: ...
    
    def getAlignmentX(self) -> float: ...
    
    def getAlignmentY(self) -> float: ...
    
    def getAnnotationsColor(self) -> Any: ...
    
    def getBackground(self) -> Any: ...
    
    def getBaseline(self, arg0: int, arg1: int) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class Tree:
    """
    sc.fiji.snt.Tree
    
    Generated from cached signatures.
    Extracted: 2025-11-02T17:38:00.112778
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def add(self, arg0: Path) -> bool: ...
    
    def applyCanvasOffset(self, arg0: float, arg1: float, arg2: float) -> None: ...
    
    def applyProperties(self, arg0: Tree) -> None: ...
    
    # Multiple overloads for assignImage
    def assignImage(self, arg0: Any) -> None: ...
    # def assignImage(self, arg0: Any) -> None: ...
    
    # Multiple overloads for assignUniqueColors
    def assignUniqueColors(self, arg0: List[Any], arg1: str) -> None: ...
    # def assignUniqueColors(self, arg0: List[Any]) -> None: ...
    
    def assignValue(self, arg0: float) -> None: ...
    
    # Multiple overloads for clone
    def clone(self) -> Tree: ...
    # def clone(self) -> Any: ...
    
    def downSample(self, arg0: float) -> None: ...
    
    def downsample(self, arg0: float) -> None: ...
    
    def fromFile(self, arg0: str) -> Tree: ...
    
    def get(self, arg0: int) -> Path: ...
    
    def getApproximatedSurface(self) -> float: ...
    
    def getApproximatedVolume(self) -> float: ...
    
    def getAssignedValue(self) -> float: ...
    
    # Multiple overloads for getBoundingBox
    def getBoundingBox(self, arg0: bool) -> BoundingBox: ...
    # def getBoundingBox(self) -> BoundingBox: ...
    
    def getColor(self) -> Any: ...
    
    # Multiple overloads for getConvexHull
    def getConvexHull(self, arg0: str) -> Any: ...
    # def getConvexHull(self) -> Any: ...
    
    # Multiple overloads for getGraph
    def getGraph(self) -> DirectedWeightedGraph: ...
    # def getGraph(self, arg0: bool) -> DirectedWeightedGraph: ...
    
    def getImpContainer(self, arg0: int, arg1: int) -> Any: ...
    
    def getLabel(self) -> str: ...
    
    def getNodes(self) -> List[Any]: ...
    
    def getNodesAsSWCPoints(self) -> List[Any]: ...
    
    def getNodesCount(self) -> int: ...
    
    def getProperties(self) -> Any: ...
    
    def getRoot(self) -> PointInImage: ...
    
    def getSWCTypeMap(self) -> Dict[str, Any]: ...
    
    # Multiple overloads for getSWCTypes
    def getSWCTypes(self, arg0: bool) -> Set[Any]: ...
    # def getSWCTypes(self) -> Set[Any]: ...
    
    # Multiple overloads for getSkeleton
    def getSkeleton(self, arg0: int) -> Any: ...
    # def getSkeleton(self) -> Any: ...
    
    # Multiple overloads for getSkeleton2D
    def getSkeleton2D(self) -> Any: ...
    # def getSkeleton2D(self, arg0: int) -> Any: ...
    
    def getSomaNodes(self) -> List[Any]: ...
    
    def indexOf(self, arg0: Path) -> int: ...
    
    def is3D(self) -> bool: ...
    
    def isAnnotated(self) -> bool: ...
    
    def isEmpty(self) -> bool: ...
    
    def list(self) -> List[Any]: ...
    
    # Multiple overloads for listFromDir
    def listFromDir(self, arg0: str) -> List[Any]: ...
    # def listFromDir(self, arg0: str, arg1: str) -> List[Any]: ...
    # def listFromDir(self, arg0: str, arg1: str, arg2: Any) -> List[Any]: ...
    
    def listFromFile(self, arg0: str) -> List[Any]: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def merge(self, arg0: Tree) -> bool: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TreeProperties:
    """
    sc.fiji.snt.TreeProperties
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.803526
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getStandardizedCompartment(self, arg0: str) -> str: ...
    
    def __getattr__(self, name: str) -> Any: ...


def version(detailed: bool) -> str: ...
def _get_detailed_version_info() -> str: ...
def print_version(detailed: bool) -> Any: ...
def show_version(detailed: bool) -> Any: ...
def info() -> Any: ...

# Imported functions
def analysis(*args: Any, **kwargs: Any) -> Any: ...
def auto_detect_and_configure(*args: Any, **kwargs: Any) -> Any: ...
def clear_fiji_path(*args: Any, **kwargs: Any) -> Any: ...
def configure_gui_safety(*args: Any, **kwargs: Any) -> Any: ...
def describe_option(*args: Any, **kwargs: Any) -> Any: ...
def display(obj: Any, **kwargs: Any) -> Any: ...
def dispose() -> None: ...
def enhance_java_object(obj: Any) -> Any: ...
def find_members(*args: Any, **kwargs: Any) -> Any: ...
def from_java(obj: Any) -> Any: ...
def get_config_info() -> Any: ...
def get_fields() -> Any: ...
def get_fiji_path() -> Any: ...
def get_fiji_status() -> Any: ...
def get_inner_classes() -> Any: ...
def get_methods() -> Any: ...
def get_option() -> Any: ...
def ij() -> Any: ...
def initialize(fiji_path: Optional[str] = None, interactive: bool = True, ensure_java: bool = True, mode: str = "headless", max_heap: Optional[str] = None, min_heap: Optional[str] = None, jvm_args: Optional[List[str]] = None) -> None: ...
def inspect(*args: Any, **kwargs: Any) -> Any: ...
def is_fiji_valid() -> bool: ...
def is_macos() -> bool: ...
def is_main_thread() -> bool: ...
def list_converters() -> List[str]: ...
def list_options(*args: Any, **kwargs: Any) -> Any: ...
def option_context(*args: Any, **kwargs: Any) -> Any: ...
def options(*args: Any, **kwargs: Any) -> Any: ...
def register_display_handler(obj_type: str, handler_func: Callable) -> None: ...
def register_snt_converters() -> bool: ...
def reset_fiji_path(*args: Any, **kwargs: Any) -> Any: ...
def reset_option(*args: Any, **kwargs: Any) -> Any: ...
def safe_gui_call(*args: Any, **kwargs: Any) -> Any: ...
def set_fiji_path(value: Any) -> None: ...
def set_option(value: Any) -> None: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...
def show(obj: Any, **kwargs: Any) -> Any: ...
def show_config_status(*args: Any, **kwargs: Any) -> Any: ...
def to_python(obj: Any) -> Any: ...
def tracing(*args: Any, **kwargs: Any) -> Any: ...
def util(*args: Any, **kwargs: Any) -> Any: ...
def viewer(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...

# Exception classes
class FijiNotFoundError(Exception): ...
class OptionError(Exception): ...