"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class Fill:
    """
    Fill - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class FillConverter:
    """
    FillConverter - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class InteractiveTracerCanvas:
    """
    InteractiveTracerCanvas - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class Path:
    """
    Path - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PathAndFillManager:
    """
    PathAndFillManager - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PathChangeListener:
    """
    PathChangeListener - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PathDownsampler:
    """
    PathDownsampler - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PathFitter:
    """
    PathFitter - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PathManagerUI:
    """
    PathManagerUI - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class SciViewSNT:
    """
    SciViewSNT - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class SNT:
    """
    SNT - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class SNTService:
    """
    SNTService - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class SNTUI:
    """
    SNTUI - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class SNTUtils:
    """
    SNTUtils - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class TracerCanvas:
    """
    TracerCanvas - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class Tree:
    """
    Tree - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class TreeProperties:
    """
    TreeProperties - No cached signatures available.
    
    Run: python dev/scripts/extract_class_signatures.py --all-classes
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def version(detailed: bool) -> str: ...
def _get_detailed_version_info() -> str: ...
def print_version(detailed: bool) -> Any: ...
def show_version(detailed: bool) -> Any: ...
def info() -> Any: ...

# Imported functions
def analysis(*args: Any, **kwargs: Any) -> Any: ...
def annotation(*args: Any, **kwargs: Any) -> Any: ...
def auto_detect_and_configure(*args: Any, **kwargs: Any) -> Any: ...
def clear_fiji_path(*args: Any, **kwargs: Any) -> Any: ...
def configure_gui_safety(*args: Any, **kwargs: Any) -> Any: ...
def describe_option(*args: Any, **kwargs: Any) -> Any: ...
def display(obj: Any, **kwargs: Any) -> Any: ...
def dispose() -> None: ...
def enhance_java_object(obj: Any) -> Any: ...
def find_members(*args: Any, **kwargs: Any) -> Any: ...
def from_java(obj: Any) -> Any: ...
def get_config_info() -> Any: ...
def get_fields() -> Any: ...
def get_fiji_path() -> Any: ...
def get_fiji_status() -> Any: ...
def get_inner_classes() -> Any: ...
def get_methods() -> Any: ...
def get_option() -> Any: ...
def ij() -> Any: ...
def initialize(fiji_path: Optional[str] = None, interactive: bool = True, ensure_java: bool = True, mode: str = "headless", max_heap: Optional[str] = None, min_heap: Optional[str] = None, jvm_args: Optional[List[str]] = None) -> None: ...
def inspect(*args: Any, **kwargs: Any) -> Any: ...
def io(*args: Any, **kwargs: Any) -> Any: ...
def is_fiji_valid() -> bool: ...
def is_macos() -> bool: ...
def is_main_thread() -> bool: ...
def list_converters() -> List[str]: ...
def list_options(*args: Any, **kwargs: Any) -> Any: ...
def option_context(*args: Any, **kwargs: Any) -> Any: ...
def options(*args: Any, **kwargs: Any) -> Any: ...
def register_display_handler(obj_type: str, handler_func: Callable) -> None: ...
def register_snt_converters() -> bool: ...
def reset_fiji_path(*args: Any, **kwargs: Any) -> Any: ...
def reset_option(*args: Any, **kwargs: Any) -> Any: ...
def safe_gui_call(*args: Any, **kwargs: Any) -> Any: ...
def set_fiji_path(value: Any) -> None: ...
def set_option(value: Any) -> None: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...
def show(obj: Any, **kwargs: Any) -> Any: ...
def show_config_status(*args: Any, **kwargs: Any) -> Any: ...
def to_python(obj: Any) -> Any: ...
def tracing(*args: Any, **kwargs: Any) -> Any: ...
def util(*args: Any, **kwargs: Any) -> Any: ...
def viewer(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...

# Exception classes
class FijiNotFoundError(Exception): ...
class OptionError(Exception): ...