"""
Runtime docstring enhancement for PySNT classes.

This module provides enhanced docstrings with JavaDoc descriptions and links
to detailed documentation for all PySNT classes.
"""

def enhance_class_docstrings():
    """Enhance docstrings for all PySNT classes with JavaDoc information."""
    import sys
    
    # Enhanced docstrings for all classes
    enhanced_docstrings = {
        "MouseLightQuerier": '"""\n    Importer for retrieving reconstructions from MouseLight\'s online database at ml-neuronbrowser.janelia.org\n    \n    **All Methods and Attributes:** See `MouseLightQuerier detailed documentation <../pysnt/io/mouselightquerier_doc.html>`_.\n    """',
        "SeedOverlayRenderer": '"""\n    Stateless renderer that draws a SeedOverlay\'s seeds onto a TracerCanvas\'s Graphics2D. Invoked from `TracerCanvas.drawOverlay(Graphics2D)` after paths are drawn so seeds appear on top.\n\nVisual conventions:\n\nColor is looked up from the overlay\'s active ColorTable using the seed\'s confidence normalized to [low, high]. Seeds outside that range are not drawn. Radius on screen is the seed\'s physical radius converted to voxels (using the active image\'s in-plane spacing) and then to canvas pixels via the current magnification. A small floor is applied so high-zoom-out seeds remain clickable. Alpha falls off with distance from the current depth slice (per-plane); seeds outside the canvas\'s eitherSide band (when just_near_slices is on) are skipped. Seeds whose 2D projection falls outside the visible canvas rectangle are skipped (the dominant performance optimization when the user is zoomed in). When the visible post-cull set exceeds SUBSAMPLE_RENDER_CAP, only the top-K seeds by confidence are drawn (full set remains available for queries).\n    \n    **All Methods and Attributes:** See `SeedOverlayRenderer detailed documentation <../pysnt/seedoverlayrenderer_doc.html>`_.\n    """',
        "InteractiveTracerCanvas": '"""\n    SNT class with method signatures.\n    \n    Available for direct import after JVM initialization.\n    Call pysnt.initialize() before using this class.\n    \n    **All Methods and Attributes:** See `InteractiveTracerCanvas detailed documentation <../pysnt/interactivetracercanvas_doc.html>`_.\n    \n    See `InteractiveTracerCanvas JavaDoc <https://javadoc.scijava.org/SNT/index.html?sc/fiji/snt/InteractiveTracerCanvas.html>`_.\n    """',
        "SNTUI": '"""\n    Implements SNT\'s main dialog.\n    \n    **All Methods and Attributes:** See `SNTUI detailed documentation <../pysnt/sntui_doc.html>`_.\n    """',
        "ZBAtlasUtils": '"""\n    Utility methods for accessing the Max Plank Zebrafish Brain Atlas (ZBA) at fishatlas.neuro.mpg.de.\n    \n    **All Methods and Attributes:** See `ZBAtlasUtils detailed documentation <../pysnt/annotation/zbatlasutils_doc.html>`_.\n    """',
        "TracerCanvas": '"""\n    Provides rendering capabilities for visualizing paths, overlays, and additional interactive elements in an ImageJ canvas.\n    \n    **All Methods and Attributes:** See `TracerCanvas detailed documentation <../pysnt/tracercanvas_doc.html>`_.\n    """',
        "BundleDetector": '"""\n    Detects regions where two paths run parallel to each other for a sustained distance, complementary to CrossoverFinder (which catches brief perpendicular near-crossings). Common use case: identifying axons bundled along the same nerve, or a path that was inadvertently hijacked by signal from a neighboring neurite running side-by-side.\n\nThis is a thin wrapper over CrossoverFinder: it reuses the entire grid/proximity/run-extraction pipeline and only inverts the angle filter. Where CrossoverFinder (with thetaMinDeg > 0) keeps only high-angle approaches (X-shaped crossings), BundleDetector uses thetaMaxDeg > 0 to keep only low-angle approaches (||-shaped sustained proximity). Defaults are also tuned for sustained runs: higher minRunNodes, similar proximity.\n\nThe output type is `CrossoverFinder.CrossoverEvent`: Callers should interpret the events as "bundled run" regions rather than crossings; the medianAngleDeg field will be small (parallel), and the index-window span will be wide (sustained).\n    \n    **All Methods and Attributes:** See `BundleDetector detailed documentation <../pysnt/util/bundledetector_doc.html>`_.\n    """',
        "SkeletonConverter": '"""\n    SNT class with method signatures.\n    \n    Available for direct import after JVM initialization.\n    Call pysnt.initialize() before using this class.\n    \n    **All Methods and Attributes:** See `SkeletonConverter detailed documentation <../pysnt/analysis/skeletonconverter_doc.html>`_.\n    \n    See `SkeletonConverter JavaDoc <https://javadoc.scijava.org/SNT/index.html?sc/fiji/snt/analysis/SkeletonConverter.html>`_.\n    """',
        "OBJMesh": '"""\n    An OBJMesh stores information about a Wavefront .obj mesh loaded into Viewer3D, with access points to its OBJFile and DrawableVBO\n    \n    **All Methods and Attributes:** See `OBJMesh detailed documentation <../pysnt/viewer/objmesh_doc.html>`_.\n    """',
        "BvvMultiSource": '"""\n    A group of BvvSource objects that are treated as a logical unit: display properties (color, range, active state) and manual transforms applied to the leader source are propagated to all follower sources.\n\nThis is particularly useful for:\n\nMultichannel images where each channel is a separate BVV source but should move together during manual registration (press T in BVV to enter manual transform mode). Multi-image workflows where multiple volumes must be grouped and manipulated as one.\n\nTransform synchronization is achieved by making all follower TransformedSources share the leader\'s fixedTransform and incrementalTransform field objects via reflection. This means any transform applied to the leader, including live T-mode (press T) dragging: It is immediately visible on all followers with no listener overhead. If reflection fails, a `renderTransformListeners` fallback is used.\n    \n    **All Methods and Attributes:** See `BvvMultiSource detailed documentation <../pysnt/viewer/bvvmultisource_doc.html>`_.\n    """',
        "InsectBrainLoader": '"""\n    Methods for retrieving reconstructions and annotations from the Insect Brain Database at insectbraindb.org *\n    \n    **All Methods and Attributes:** See `InsectBrainLoader detailed documentation <../pysnt/io/insectbrainloader_doc.html>`_.\n    """',
        "TreeUtils": '"""\n    Static utilities for Trees.\n    \n    **All Methods and Attributes:** See `TreeUtils detailed documentation <../pysnt/util/treeutils_doc.html>`_.\n    """',
        "NodeProfiler": '"""\n    Command to retrieve node profiles (plots of voxel intensities sampled across Path nodes).\n    \n    **All Methods and Attributes:** See `NodeProfiler detailed documentation <../pysnt/analysis/nodeprofiler_doc.html>`_.\n    """',
        "SNTTable": '"""\n    Extension of DefaultGenericTable with (minor) scripting conveniences.\n    \n    **All Methods and Attributes:** See `SNTTable detailed documentation <../pysnt/analysis/snttable_doc.html>`_.\n    """',
        "Tubeness": '"""\n    Computes a tubeness (vesselness) filter on a multi-dimensional image using multi-scale eigenvalue analysis of the Hessian matrix. This is useful for enhancing and segmenting curvilinear structures such as neurites and blood vessels.\n\nBased on: Y. Sato, S. Nakajima, N. Shiraga, H. Atsumi, S. Yoshida, T. Koller, G. Gerig, and R. Kikinis, "Three-dimensional multi-scale line filter for segmentation and visualization of curvilinear structures in medical images," Med. Image Anal., vol. 2, no. 2, pp. 143–168, June 1998.\n    \n    **All Methods and Attributes:** See `Tubeness detailed documentation <../pysnt/filter/tubeness_doc.html>`_.\n    """',
        "PathChangeListener": '"""\n    SNT class with method signatures.\n    \n    Available for direct import after JVM initialization.\n    Call pysnt.initialize() before using this class.\n    \n    **All Methods and Attributes:** See `PathChangeListener detailed documentation <../pysnt/pathchangelistener_doc.html>`_.\n    \n    See `PathChangeListener JavaDoc <https://javadoc.scijava.org/SNT/index.html?sc/fiji/snt/PathChangeListener.html>`_.\n    """',
        "ImpUtils": '"""\n    Static utilities for handling and manipulation of ImagePluss\n    \n    **All Methods and Attributes:** See `ImpUtils detailed documentation <../pysnt/util/imputils_doc.html>`_.\n    """',
        "ImgUtils": '"""\n    Static utilities for handling and manipulation of `RandomAccessibleInterval`s\n    \n    **All Methods and Attributes:** See `ImgUtils detailed documentation <../pysnt/util/imgutils_doc.html>`_.\n    """',
        "FillerThread": '"""\n    Seeded-volume segmentation via single-source shortest paths. Path nodes are used as seed points in an open-ended variant of Dijkstra\'s algorithm. The threshold sets the maximum allowable distance for a node to be included in the Fill. This distance is represented in the g-score of a node, which is the length of the shortest path from a seed point to that node. The magnitudes of these distances are heavily dependent on the supplied cost function Cost, so the threshold should be set with a particular cost function in mind. It often helps to adjust the threshold interactively.\n    \n    **All Methods and Attributes:** See `FillerThread detailed documentation <../pysnt/tracing/fillerthread_doc.html>`_.\n    """',
        "Frangi": '"""\n    A.F. Frangi, W.J. Niessen, K.L. Vincken, M.A. Viergever (1998). Multiscale vessel enhancement filtering. In Medical Image Computing and Computer-Assisted Intervention - MICCAI\'98, W.M. Wells, A. Colchester and S.L. Delp (Eds.), Lecture Notes in Computer Science, vol. 1496 - Springer Verlag, Berlin, Germany, pp. 130-137.\n    \n    **All Methods and Attributes:** See `Frangi detailed documentation <../pysnt/filter/frangi_doc.html>`_.\n    """',
        "NeurolucidaImporter": '"""\n    Importer for Neurolucida XML files (Neuromorphological File Specification / NMF format). Parses <tree> elements into SNT Path/Tree objects and <marker> elements into bookmark data (centroid coordinates). Contours and vessels are skipped in this implementation.\n    \n    **All Methods and Attributes:** See `NeurolucidaImporter detailed documentation <../pysnt/io/neurolucidaimporter_doc.html>`_.\n    """',
        "PathProfiler": '"""\n    Command to retrieve Path profiles (plots of voxel intensities values along a Path)\n    \n    **All Methods and Attributes:** See `PathProfiler detailed documentation <../pysnt/analysis/pathprofiler_doc.html>`_.\n    """',
        "AllenUtils": '"""\n    Utility methods for accessing/handling AllenCompartments\n    \n    **All Methods and Attributes:** See `AllenUtils detailed documentation <../pysnt/annotation/allenutils_doc.html>`_.\n    """',
        "Tree": '"""\n    Utility class to access a Collection of Paths (typically a complete reconstruction). A Tree is the preferred way to group, access and manipulate Paths that share something in common, specially when scripting SNT. Note that a "Tree" here is literally a collection of Paths. Very few restrictions are imposed on its topology, although it is generally assumed that the Collection of paths describes a single-rooted structure with no loops.\n    \n    **All Methods and Attributes:** See `Tree detailed documentation <../pysnt/tree_doc.html>`_.\n    """',
        "BvvUtils": '"""\n    Package-private utility methods shared across BVV-related classes (Bvv, ChannelUnmixingCard, etc.).\n    \n    **All Methods and Attributes:** See `BvvUtils detailed documentation <../pysnt/viewer/bvvutils_doc.html>`_.\n    """',
        "SNTColor": '"""\n    A simple class for handling Colors including the ability to map an AWT Color to a SWC type integer tag.\n    \n    **All Methods and Attributes:** See `SNTColor detailed documentation <../pysnt/util/sntcolor_doc.html>`_.\n    """',
        "PathFitter": '"""\n    Class for fitting circular cross-sections around existing nodes of a Path in order to compute radii (node thickness) and midpoint refinement of existing coordinates. Thread Safety: When fitting multiple paths in parallel: 1. Call call() in parallel (thread-safe) 2. Call applyFit() sequentially (modifies path hierarchy)\n\nExample: \n```\nList<PathFitter> fitters = paths.stream()\n     .map(p -> new PathFitter(img, p))\n     .collect(Collectors.toList());\n <p>\n // Parallel fitting\n fitters.parallelStream().forEach(PathFitter::call);\n <p>\n // Sequential application\n fitters.forEach(PathFitter::applyFit);\n```\n    \n    **All Methods and Attributes:** See `PathFitter detailed documentation <../pysnt/pathfitter_doc.html>`_.\n    """',
        "TreeProperties": '"""\n    Allows standardized metadata to be associated to a Tree.\n    \n    **All Methods and Attributes:** See `TreeProperties detailed documentation <../pysnt/treeproperties_doc.html>`_.\n    """',
        "WekaModelLoader": '"""\n    GUI command for Loading pre-trained models from Labkit/TWS as secondary image layer.\n    \n    **All Methods and Attributes:** See `WekaModelLoader detailed documentation <../pysnt/io/wekamodelloader_doc.html>`_.\n    """',
        "VFBUtils": '"""\n    Utility methods for accessing/handling Virtual Fly Brain (VFB) annotations\n    \n    **All Methods and Attributes:** See `VFBUtils detailed documentation <../pysnt/annotation/vfbutils_doc.html>`_.\n    """',
        "SearchThread": '"""\n    Implements a common thread that explores the image using a variety of strategies, e.g., to trace tubular structures or surfaces.\n    \n    **All Methods and Attributes:** See `SearchThread detailed documentation <../pysnt/tracing/searchthread_doc.html>`_.\n    """',
        "SeedManager": '"""\n    Reusable JPanel that controls a SeedOverlay: visibility, LUT, confidence range, transparency, counters, CSV import/export/clear, plus an inline JTable for browsing and editing individual seeds. Used as the content of SNTUI\'s "Seeds" tab. Multiple instances can coexist on the same SeedOverlay; each registers its own listener and synchronizes via the overlay (the data model is the source of truth).\n\nCaller must invoke dispose() when the panel is removed from its parent so the overlay and table-model listeners are unregistered.\n    \n    **All Methods and Attributes:** See `SeedManager detailed documentation <../pysnt/seedmanager_doc.html>`_.\n    """',
        "PointInImage": '"""\n    Defines a Point in an image, a node of a traced Path. Coordinates are always expressed in real-world coordinates.\n    \n    **All Methods and Attributes:** See `PointInImage detailed documentation <../pysnt/util/pointinimage_doc.html>`_.\n    """',
        "NodeStatistics": '"""\n    Computes summary and descriptive statistics from a Collection of nodes, including convenience methods to plot distributions of such data.\n    \n    **All Methods and Attributes:** See `NodeStatistics detailed documentation <../pysnt/analysis/nodestatistics_doc.html>`_.\n    """',
        "ColorMaps": '"""\n    Utilities for colormaps and IJ lookup tables\n    \n    **All Methods and Attributes:** See `ColorMaps detailed documentation <../pysnt/util/colormaps_doc.html>`_.\n    """',
        "MultiTreeStatistics": '"""\n    Computes summary and descriptive statistics from univariate properties of Tree groups. For analysis of individual Trees use TreeStatistics.\n    \n    **All Methods and Attributes:** See `MultiTreeStatistics detailed documentation <../pysnt/analysis/multitreestatistics_doc.html>`_.\n    """',
        "FlyCircuitLoader": '"""\n    Absurdly simple importer for retrieving SWC data from FlyCircuit.\n    \n    **All Methods and Attributes:** See `FlyCircuitLoader detailed documentation <../pysnt/io/flycircuitloader_doc.html>`_.\n    """',
        "FillConverter": '"""\n    Map filled nodes from a Collection of FillerThreads to and between RandomAccessibles.\n    \n    **All Methods and Attributes:** See `FillConverter detailed documentation <../pysnt/fillconverter_doc.html>`_.\n    """',
        "PCAnalyzer": '"""\n    Utility class for performing Principal Component Analysis (PCA) on various SNT data structures including Trees, Paths, and collections of SNTPoints.\n\nThis class provides methods to compute the principal axes of 3D point data, which represent the directions of maximum variance in the data. This is useful for analyzing the overall orientation and shape characteristics of neuronal structures, meshes, and other 3D geometries.\n    \n    **All Methods and Attributes:** See `PCAnalyzer detailed documentation <../pysnt/analysis/pcanalyzer_doc.html>`_.\n    """',
        "SNTChart": '"""\n    Extension of ChartPanel modified for scientific publications and convenience methods for plot annotations.\n    \n    **All Methods and Attributes:** See `SNTChart detailed documentation <../pysnt/analysis/sntchart_doc.html>`_.\n    """',
        "InsectBrainUtils": '"""\n    Utility methods for retrieving species, brain, and neuron data from the Insect Brain Database\n    \n    **All Methods and Attributes:** See `InsectBrainUtils detailed documentation <../pysnt/annotation/insectbrainutils_doc.html>`_.\n    """',
        "AStarRefiner": '"""\n    Post-hoc A* re-tracing of a single, already-existing Path: treats the path\'s current nodes as waypoints and re-derives the geometry between them via \n```\nSNT.autoTraceSync(List, sc.fiji.snt.util.PointInImage, SNT.SearchSettingsSnapshot)\n```\n, using either the cost function/search parameters currently configured on the active SNT instance, or a frozen `SNT.SearchSettingsSnapshot` shared across a whole batch (see `AStarRefiner(SNT, Path, SNT.SearchSettingsSnapshot)`).\n\nIntended for manually-traced paths against data streamed from disk/network, where running A* interactively may be too slow to be practical. See PathManagerUI\'s "Refine" menu ("Re-trace with A*...").\n\ncall() is thread-safe for parallel execution across paths (it does not modify the original path, and calls \n```\nSNT.autoTraceSync(java.util.List<sc.fiji.snt.util.SNTPoint>, sc.fiji.snt.util.PointInImage)\n```\n rather than the interactive tracing entry points, so concurrent workers do not serialize behind the single-threaded pool used by interactive tracing). apply() must be called sequentially afterward to commit the result via `Path.replaceNodes(Path)`, which also reconciles this path\'s own branch point (if it has a parent) and any of its children\'s branch points against the new geometry.\n    \n    **All Methods and Attributes:** See `AStarRefiner detailed documentation <../pysnt/astarrefiner_doc.html>`_.\n    """',
        "PathDownsampler": '"""\n    This is an implementation of the Ramer-Douglas-Peucker algorithm for simplifying a curve represented by line-segments, as described here\n    \n    **All Methods and Attributes:** See `PathDownsampler detailed documentation <../pysnt/pathdownsampler_doc.html>`_.\n    """',
        "PersistenceAnalyzer": '"""\n    Performs persistent homology analysis on neuronal Trees.\n\nThis class implements the algorithm described in Kanari, L. et al. "A Topological Representation of Branching Neuronal Morphologies" (Neuroinformatics 16, 3–13, 2018) to extract topological features from neuronal morphologies.\n\nCore Concepts\n\nFilter Functions: Mathematical functions that assign scalar values to each node in the tree based on various morphological properties (distance from root, branch order, spatial coordinates, etc.).\n\nPersistence Diagram: A collection of 2D points (birth, death) representing when topological features (branches) appear and disappear during a filtration process. Each point corresponds to a branch in the neuronal tree.\n\nPersistence: The "lifespan" of a topological feature, calculated as death - birth. High persistence indicates morphologically significant branches, while low persistence may represent noise or minor branches.\n\nSupported Filter Functions\n\nGeodesic: Path distance from node to root along the tree structure Radial: Euclidean (straight-line) distance from node to root Centrifugal: Reverse Strahler number (branch order from tips) Path Order: SNT path order hierarchy X, Y, Z: Spatial coordinates for directional analysis\n\nUsage Example \n```\n// Create analyzer for a neuronal tree\n PersistenceAnalyzer analyzer = new PersistenceAnalyzer(tree);\n \n // Get persistence diagram using geodesic distance\n List<List<Double>> diagram = analyzer.getDiagram("geodesic");\n \n // Each inner list contains [birth, death] values\n for (List<Double> pair : diagram) {\n     double birth = pair.get(0);\n     double death = pair.get(1);\n     double persistence = death - birth;\n     System.out.println("Branch: birth=" + birth + ", death=" + death + ", persistence=" + persistence);\n }\n \n // Get persistence landscape\n double[] landscape = analyzer.getLandscape("geodesic", 5, 100);\n```\n    \n    **All Methods and Attributes:** See `PersistenceAnalyzer detailed documentation <../pysnt/analysis/persistenceanalyzer_doc.html>`_.\n    """',
        "BiSearch": '"""\n    A flexible implementation of the bidirectional heuristic search algorithm described in Pijls, W.H.L.M., Post, H., 2009. "Yet another bidirectional algorithm for shortest paths," Econometric Institute Research Papers EI 2009-10, Erasmus University Rotterdam, Erasmus School of Economics (ESE), Econometric Institute.\n\nThe search distance function (Cost) and heuristic estimate (Heuristic) are supplied by the caller.\n    \n    **All Methods and Attributes:** See `BiSearch detailed documentation <../pysnt/tracing/bisearch_doc.html>`_.\n    """',
        "Path": '"""\n    This class represents a traced segment (i.e., a Path) in a reconstruction. It has methods to manipulate its points (nodes) with sup-pixel accuracy, including drawing them onto threePane-style canvases, etc.\n\nPaths are non-branching sequences of adjacent points (including diagonals) in the image. Branches and joins are supported by attributes of paths that specify that they begin on (or end on) other paths.\n\nIn SNT, a Path can exist in two versions or flavors: itself and a fitted version generated by PathFitter. Because fitting may fail around certain nodes, the fitted version may have a different number of nodes relatively to its non-fitted version\n    \n    **All Methods and Attributes:** See `Path detailed documentation <../pysnt/path_doc.html>`_.\n    """',
        "BoundingBox": '"""\n    A BoundingBox contains information (including spatial calibration) of a tracing canvas bounding box, i.e., the minimum bounding cuboid containing all nodes (SNTPoints) of a reconstructed structure.\n    \n    **All Methods and Attributes:** See `BoundingBox detailed documentation <../pysnt/util/boundingbox_doc.html>`_.\n    """',
        "BiSearchNode": '"""\n    A SearchNode which can maintain both a from-start and from-goal search state.\n    \n    **All Methods and Attributes:** See `BiSearchNode detailed documentation <../pysnt/tracing/bisearchnode_doc.html>`_.\n    """',
        "TreeToRaster": '"""\n    Rasterizes a Tree into a 3D image using frustum (truncated-cone) geometry with partial-volume supersampling. Each segment between consecutive nodes is modeled as a frustum whose radii are linearly interpolated from the node radii. This produces a volumetric rendering that respects the thickness of each neurite, unlike the skeleton-based rasterization in Tree.getSkeleton().\n\nOptionally, Poisson shot noise and Gaussian blur (to simulate spatially correlated noise) can be applied, producing realistic synthetic fluorescence microscopy images.\n\nOptionally, voxel intensities can be modulated by local neurite thickness via `setThicknessModulation(double)`, producing brighter thick neurites and dimmer thin ones.\n\nPass 2 (partial-volume supersampling) and subsequent passes are parallelized across z-slices for improved performance. A spatial grid is used for frustum lookups to reduce computation costs.\n\nInspired by SWC2IMG (E. Meijering, imagescience.org).\n    \n    **All Methods and Attributes:** See `TreeToRaster detailed documentation <../pysnt/util/treetoraster_doc.html>`_.\n    """',
        "ShollAnalyzer": '"""\n    Class to retrieve Sholl metrics from a Tree.\n    \n    **All Methods and Attributes:** See `ShollAnalyzer detailed documentation <../pysnt/analysis/shollanalyzer_doc.html>`_.\n    """',
        "MouseLightLoader": '"""\n    Methods for retrieving reconstructions from MouseLight\'s online database at ml-neuronbrowser.janelia.org *\n    \n    **All Methods and Attributes:** See `MouseLightLoader detailed documentation <../pysnt/io/mouselightloader_doc.html>`_.\n    """',
        "PathAndFillManager": '"""\n    The PathAndFillManager is responsible for importing, handling and managing of Paths and Fills. Typically, a PathAndFillManager is accessed from a SNT instance, but accessing a PathAndFillManager directly is useful for batch/headless operations.\n    \n    **All Methods and Attributes:** See `PathAndFillManager detailed documentation <../pysnt/pathandfillmanager_doc.html>`_.\n    """',
        "Fill": '"""\n    Defines a filled structure.\n    \n    **All Methods and Attributes:** See `Fill detailed documentation <../pysnt/fill_doc.html>`_.\n    """',
        "TreeStatistics": '"""\n    Computes summary and descriptive statistics from properties of Paths and Nodes in a Tree, including convenience methods to plot distributions of such data. For analysis of groups of Trees have a look at MultiTreeStatistics and `GroupedTreeStatistics`.\n    \n    **All Methods and Attributes:** See `TreeStatistics detailed documentation <../pysnt/analysis/treestatistics_doc.html>`_.\n    """',
        "SearchNode": '"""\n    Interface representing a node in 3D space that can be used in pathfinding and search algorithms.\n    \n    **All Methods and Attributes:** See `SearchNode detailed documentation <../pysnt/tracing/searchnode_doc.html>`_.\n    """',
        "Viewer3D": '"""\n    Implements SNT\'s Reconstruction Viewer. Relies heavily on the org.jzy3d package.\n    \n    **All Methods and Attributes:** See `Viewer3D detailed documentation <../pysnt/viewer/viewer3d_doc.html>`_.\n    """',
        "SNTPoint": '"""\n    Classes extend this interface implement a point in a 3D space, always using real world coordinates.\n    \n    **All Methods and Attributes:** See `SNTPoint detailed documentation <../pysnt/util/sntpoint_doc.html>`_.\n    """',
        "PathStatistics": '"""\n    A specialized version of TreeStatistics for analyzing individual paths without considering their connectivity relationships.\n\nPathStatistics provides morphometric analysis of neuronal paths while treating each path as an independent entity, rather than as part of a connected tree structure.\n\nKey differences from TreeStatistics:\n\nNo graph conversion - paths are analyzed independently Branch-related metrics are redefined to work with individual paths Supports path-specific measurements like Path ID and number of children Provides individual path measurement capabilities\n\nExample usage: \n```\n// Analyze a single path\n PathStatistics stats = new PathStatistics(path);\n double length = stats.getMetric("Path length").doubleValue();\n \n // Analyze multiple paths independently\n Collection<Path> paths = getPaths();\n PathStatistics multiStats = new PathStatistics(paths, "My Analysis");\n multiStats.measureIndividualPaths(Arrays.asList("Path length", "N. nodes"), true);\n```\n    \n    **All Methods and Attributes:** See `PathStatistics detailed documentation <../pysnt/analysis/pathstatistics_doc.html>`_.\n    """',
        "GroupedTreeStatistics": '"""\n    Computes statistics from Tree groups.\n    \n    **All Methods and Attributes:** See `GroupedTreeStatistics detailed documentation <../pysnt/analysis/groupedtreestatistics_doc.html>`_.\n    """',
        "StrahlerAnalyzer": '"""\n    Class to perform Horton-Strahler analysis on a Tree.\n    \n    **All Methods and Attributes:** See `StrahlerAnalyzer detailed documentation <../pysnt/analysis/strahleranalyzer_doc.html>`_.\n    """',
        "Viewer2D": '"""\n    Class for rendering Trees as 2D plots that can be exported as SVG, PNG or PDF.\n    \n    **All Methods and Attributes:** See `Viewer2D detailed documentation <../pysnt/viewer/viewer2d_doc.html>`_.\n    """',
        "RootAngleAnalyzer": '"""\n    Class to perform Root angle analysis on a Tree according to Bird and Cuntz 2019, PMID 31167149.\n    \n    **All Methods and Attributes:** See `RootAngleAnalyzer detailed documentation <../pysnt/analysis/rootangleanalyzer_doc.html>`_.\n    """',
        "TracerThread": '"""\n    SNT\'s default tracer thread: explores between two points in an image, doing an A* search with a choice of distance measures.\n    \n    **All Methods and Attributes:** See `TracerThread detailed documentation <../pysnt/tracing/tracerthread_doc.html>`_.\n    """',
        "AllenCompartment": '"""\n    Defines an Allen Reference Atlas (ARA) [Allen Mouse Common Coordinate Framework] annotation. A Compartment is defined by either a UUID (as per MouseLight\'s database) or its unique integer identifier. To improve performance, a compartment\'s metadata (reference to its mesh, its aliases, etc.) are not loaded at initialization, but retrieved only when such getters are called.\n    \n    **All Methods and Attributes:** See `AllenCompartment detailed documentation <../pysnt/annotation/allencompartment_doc.html>`_.\n    """',
        "SpectralSimilarity": '"""\n    Computes a spectral similarity map from a multichannel (e.g., Brainbow) image. For each voxel, the output encodes how well the voxel\'s channel-intensity vector matches a reference color vector. The output is a scalar image suitable for use as a secondary tracing layer.\n\nThe per-voxel score combines two terms:\n\nCosine similarity: dot product of unit-normalized voxel and reference color vectors (1 = identical direction, 0 = orthogonal) Intensity factor: sigmoid falloff based on how much the voxel\'s total intensity deviates from the reference intensity. This prevents bright background or dim noise from producing high scores\n\nThe final output is `cosineSimilarity × intensityFactor`, scaled to [0, 1]. High values indicate voxels that match the target neuron\'s color and brightness.\n\nThe input image is a 4D (X, Y, Z, C) `RandomAccessibleInterval` where the last dimension is channels. The output is a 3D (X, Y, Z) scalar image.\n\nThis filter is designed for integration with SNT\'s secondary layer tracing infrastructure, where any standard cost function (e.g., Reciprocal) applied to the output produces spectrally-aware path searches.\n\nThe color-vector approach to neurite identification in multichannel images is also validated in:\n\nLeiwe et al., "Automated neuronal reconstruction with super-multicolour Tetbow labelling and threshold-based clustering of colour hues", Nat Commun 15, 5279 (2024). doi:10.1038/s41467-024-49455-y\n    \n    **All Methods and Attributes:** See `SpectralSimilarity detailed documentation <../pysnt/filter/spectralsimilarity_doc.html>`_.\n    """',
        "SNTService": '"""\n    Service for accessing and scripting the active instance of SNT.\n    \n    **All Methods and Attributes:** See `SNTService detailed documentation <../pysnt/sntservice_doc.html>`_.\n    """',
        "SciViewSNT": '"""\n    Bridges SNT to SciView, allowing Trees to be rendered as scenery objects\n    \n    **All Methods and Attributes:** See `SciViewSNT detailed documentation <../pysnt/sciviewsnt_doc.html>`_.\n    """',
        "RemoteSWCLoader": '"""\n    Importers downloading remote SWC files should extend this interface.\n    \n    **All Methods and Attributes:** See `RemoteSWCLoader detailed documentation <../pysnt/io/remoteswcloader_doc.html>`_.\n    """',
        "ConvexHull3D": '"""\n    Convex hull analysis in 3D.\n    \n    **All Methods and Attributes:** See `ConvexHull3D detailed documentation <../pysnt/analysis/convexhull3d_doc.html>`_.\n    """',
        "NodeColorMapper": '"""\n    Class for color coding of NodeStatistics results.\n    \n    **All Methods and Attributes:** See `NodeColorMapper detailed documentation <../pysnt/analysis/nodecolormapper_doc.html>`_.\n    """',
        "InsectBrainCompartment": '"""\n    Returns the compartment\'s acronym.\n    \n    **All Methods and Attributes:** See `InsectBrainCompartment detailed documentation <../pysnt/annotation/insectbraincompartment_doc.html>`_.\n    """',
        "PathStraightener": '"""\n    Command to "straighten" an image using Path coordinates.\n    \n    **All Methods and Attributes:** See `PathStraightener detailed documentation <../pysnt/analysis/pathstraightener_doc.html>`_.\n    """',
        "MultiViewer3D": '"""\n    Class for rendering individual Viewer3Ds as a multi-panel montage.\n    \n    **All Methods and Attributes:** See `MultiViewer3D detailed documentation <../pysnt/viewer/multiviewer3d_doc.html>`_.\n    """',
        "SWCPoint": '"""\n    Defines a node in an SWC reconstruction. The SWC file format is detailed here.\n    \n    **All Methods and Attributes:** See `SWCPoint detailed documentation <../pysnt/util/swcpoint_doc.html>`_.\n    """',
        "CrossoverFinder": '"""\n    Utility to detect crossover locations between paths: spatially close locations between paths that look like intersections in the image but are not topological joins in the traced graph.\n\nHere, a crossover is defined as a spatial location where two distinct paths approach within a distance threshold (in real units) for at least minRunNodes consecutive node pairs, but do not share an actual tracing node at that location. Optional geometric filtering by crossing angle is supported.\n\nUsage: \n```\nCrossoverFinder.Config cfg = new CrossoverFinder.Config()\n       .proximity(2.0)          // spatial threshold in spatially calibrated units (e.g., microns)\n       .thetaMinDeg(25)         // optional minimum crossing angle (0 to disable)\n       .minRunNodes(2)          // consecutive near-node pairs to accept a crossover event candidate\n       .sameCTOnly(true)        // ignore pairs from different channel/time\n       .includeSelfCrossovers(false) // whether crossover events within the same path should be detected\n   List<CrossoverFinder.CrossoverEvent> events = CrossoverFinder.find(paths, cfg);\n```\n    \n    **All Methods and Attributes:** See `CrossoverFinder detailed documentation <../pysnt/util/crossoverfinder_doc.html>`_.\n    """',
        "NeuroMorphoLoader": '"""\n    Importer for retrieving SWC data from neuromorpho.org.\n    \n    **All Methods and Attributes:** See `NeuroMorphoLoader detailed documentation <../pysnt/io/neuromorpholoader_doc.html>`_.\n    """',
        "MultiTreeColorMapper": '"""\n    Class for color coding groups of Trees.\n\nAfter a mapping property and a color table (LUT) are specified, the mapping proceeds as follows: 1) Each Tree in the group is measured for the mapping property; 2) each measurement is mapped to a LUT entry that is used to color each Tree. Mapping limits can be optionally specified\n    \n    **All Methods and Attributes:** See `MultiTreeColorMapper detailed documentation <../pysnt/analysis/multitreecolormapper_doc.html>`_.\n    """',
        "SNT": '"""\n    Implements the SNT plugin.\n    \n    **All Methods and Attributes:** See `SNT detailed documentation <../pysnt/snt_doc.html>`_.\n    """',
        "DefaultSearchNode": '"""\n    A SearchNode which can maintain both a from-start and from-goal search state.\n    \n    **All Methods and Attributes:** See `DefaultSearchNode detailed documentation <../pysnt/tracing/defaultsearchnode_doc.html>`_.\n    """',
        "PathManagerUI": '"""\n    Implements the Path Manager Dialog.\n    \n    **All Methods and Attributes:** See `PathManagerUI detailed documentation <../pysnt/pathmanagerui_doc.html>`_.\n    """',
        "Annotation3D": '"""\n    An Annotation3D is a triangulated surface or a cloud of points (scatter) rendered in Viewer3D that can be used to highlight nodes in a Tree or locations in a mesh.\n    \n    **All Methods and Attributes:** See `Annotation3D detailed documentation <../pysnt/viewer/annotation3d_doc.html>`_.\n    """',
        "ConvexHullAnalyzer": '"""\n    Class for Convex Hull measurements of a Tree.\n    \n    **All Methods and Attributes:** See `ConvexHullAnalyzer detailed documentation <../pysnt/analysis/convexhullanalyzer_doc.html>`_.\n    """',
        "SNTUtils": '"""\n    Static utilities for SNT\n    \n    **All Methods and Attributes:** See `SNTUtils detailed documentation <../pysnt/sntutils_doc.html>`_.\n    """',
        "MultiViewer2D": '"""\n    Class for rendering montages of Trees as 2D plots that can be exported as SVG, PNG or PDF.\n    \n    **All Methods and Attributes:** See `MultiViewer2D detailed documentation <../pysnt/viewer/multiviewer2d_doc.html>`_.\n    """',
        "ConvexHull2D": '"""\n    Computes the convex hull of a set of 2D points.\n    \n    **All Methods and Attributes:** See `ConvexHull2D detailed documentation <../pysnt/analysis/convexhull2d_doc.html>`_.\n    """',
        "TreeColorMapper": '"""\n    Class for color coding Trees.\n    \n    **All Methods and Attributes:** See `TreeColorMapper detailed documentation <../pysnt/analysis/treecolormapper_doc.html>`_.\n    """',
        "PathResult": '"""\n    SNT class with method signatures.\n    \n    Available for direct import after JVM initialization.\n    Call pysnt.initialize() before using this class.\n    \n    **All Methods and Attributes:** See `PathResult detailed documentation <../pysnt/tracing/pathresult_doc.html>`_.\n    \n    See `PathResult JavaDoc <https://javadoc.scijava.org/SNT/index.html?sc/fiji/snt/tracing/PathResult.html>`_.\n    """',
    }
    
    # Apply enhanced docstrings to classes in pysnt modules
    _apply_enhanced_docstrings(enhanced_docstrings)

def _apply_enhanced_docstrings(enhanced_docstrings):
    """Apply enhanced docstrings to classes in loaded modules."""
    import sys
    import os
    from pathlib import Path
    
    # Automatically discover all pysnt submodules
    module_names = ['pysnt']  # Start with main module
    
    # Find the pysnt package directory
    try:
        # Try to find pysnt in sys.path or relative to this file
        pysnt_dir = None
        for path in sys.path:
            potential_dir = Path(path) / 'pysnt'
            if potential_dir.is_dir() and (potential_dir / '__init__.py').exists():
                pysnt_dir = potential_dir
                break
        
        # If not found in sys.path, try relative to common locations
        if not pysnt_dir:
            # Try relative to this file (for when generating docs)
            script_dir = Path(__file__).parent.parent.parent.parent  # Go up to project root
            potential_dir = script_dir / 'src' / 'pysnt'
            if potential_dir.is_dir() and (potential_dir / '__init__.py').exists():
                pysnt_dir = potential_dir
        
        # Discover submodules
        if pysnt_dir:
            for item in sorted(pysnt_dir.iterdir()):
                if item.is_dir() and not item.name.startswith('_') and not item.name.startswith('.'):
                    # Check if it's a Python package (has __init__.py)
                    if (item / '__init__.py').exists():
                        module_names.append(f'pysnt.{item.name}')
    except Exception:
        # If discovery fails, fall back to known modules
        module_names = [
            'pysnt',
            'pysnt.analysis',
            'pysnt.annotation',
            'pysnt.converters',
            'pysnt.display',
            'pysnt.gui',
            'pysnt.io',
            'pysnt.tracing',
            'pysnt.util',
            'pysnt.viewer'
        ]
    
    for module_name in module_names:
        # Try to get the module from sys.modules, or import it
        module = None
        if module_name in sys.modules:
            module = sys.modules[module_name]
        else:
            # Try to import the module
            try:
                module = __import__(module_name, fromlist=[''])
            except (ImportError, Exception):
                # Module not available, skip it
                continue
        
        if module:
            for class_name, enhanced_docstring in enhanced_docstrings.items():
                if hasattr(module, class_name):
                    class_obj = getattr(module, class_name)
                    if hasattr(class_obj, '__doc__'):
                        class_obj.__doc__ = enhanced_docstring
                        #print(f"Enhanced docstring for {module_name}.{class_name}")

# Auto-enhance when this module is imported
enhance_class_docstrings()
