"""
Type stubs for config.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

class OptionError:
    pass

class _Option:
    def __init__(self: Any, key: str, default_value: Any, doc: str, validator: Optional[Callable], callback: Optional[Callable]) -> Any: ...
    def value(self: Any) -> Any: ...
    def value(self: Any, val: Any) -> Any: ...

def _chart_format_validator(value: str) -> str: ...

def _table_display_validator(value: str) -> str: ...

def _positive_int_validator(value: int) -> int: ...

def _dpi_validator(value: int) -> int: ...

def _layout_algorithm_validator(value: str) -> str: ...

def _graph_type_validator(value: str) -> str: ...

def _java_logging_callback(key: str, old_value: Any, new_value: Any) -> None: ...

def _register_option(key: str, default_value: Any, doc: str, validator: Optional[Callable], callback: Optional[Callable]) -> Any: ...

def get_option(key: str) -> Any: ...

def set_option(key: str, value: Any) -> None: ...

def reset_option(key: str) -> None: ...

def describe_option(key: Optional[str]) -> None: ...

def _describe_single_option(key: str) -> None: ...

def list_options() -> List[str]: ...

def option_context(**kwargs: Any) -> Any: ...

class _OptionContext:
    def __init__(self: Any, **kwargs: Any) -> Any: ...
    def __enter__(self: Any) -> Any: ...
    def __exit__(self: Any, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...

class _Config:
    def __getattr__(self: Any, name: Any) -> Any: ...
    def __setattr__(self: Any, name: Any, value: Any) -> Any: ...

options: Any