"""
Type stubs for converters.py

Auto-generated stub file.
"""

from typing import Any

logger: Any
class SNTObject:
    pass

def _get_java_class_name(obj: Any) -> str: ...

def _is_snt_object(obj: Any) -> bool: ...

def _is_snt_chart_object(obj: Any) -> bool: ...

def _is_gui_object(obj: Any) -> bool: ...

def _is_xarray_object(obj: Any) -> bool: ...

def _is_snt_chart(obj: Any) -> bool: ...

def _is_snt_table(obj: Any) -> bool: ...

def _convert_snt_chart(chart: Any, **kwargs: Any) -> SNTObject: ...

def _convert_single_snt_chart(chart: Any, format_type: str, temp_dir: str, scale: float) -> Figure: ...

def _convert_combined_snt_chart(chart: Any, format_type: str, temp_dir: str, scale: float, max_panels: int, panel_layout: str) -> Figure: ...

def _create_matplotlib_figure_from_image(img_array: Any, figsize: Any, title: Any, dpi: Any) -> Any: ...

def _png_to_matplotlib(png_file: str, figsize: Any) -> Figure: ...

def _convert_snt_table(table: Any, **kwargs: Any) -> SNTObject: ...

def _svg_to_matplotlib(svg_file: Any, dpi: Any, figsize: Any, background: Any) -> Any: ...

def _pdf_to_matplotlib(pdf_file: Any, page: Any, dpi: Any, figsize: Any) -> Any: ...

SNT_CONVERTERS: Any
def register_snt_converters() -> Any: ...

def _get_display_handler(obj: Any) -> Any: ...

def display(obj: Any, **kwargs: Any) -> Any: ...

def _handle_snt_object_display(obj: Any, **kwargs: Any) -> Any: ...

def _display_snt_object(obj: Any, **kwargs: Any) -> Any: ...

def _display_imageplus(obj: Any, **kwargs: Any) -> Any: ...

def _display_with_auto_conversion(obj: Any, **kwargs: Any) -> Any: ...

def _show_matplotlib_figure(fig: Any, **kwargs: Any) -> bool: ...

def _display_matplotlib_figure(fig: Figure, **kwargs: Any) -> None: ...

def _display_xarray(xarr: Any, **kwargs: Any) -> None: ...

def _show_pandasgui_dataframe(df: Any, title: Any, **kwargs: Any) -> bool: ...

def _display_dataset_as_dataframe(dataset: Any, **kwargs: Any) -> bool: ...

def _create_dataset_summary_plot(dataset: Any, display_vars: List[str], title: str, figsize: tuple) -> bool: ...

def _create_dataset_distribution_plot(dataset: Any, display_vars: List[str], title: str, figsize: tuple) -> bool: ...

def _create_dataset_correlation_plot(dataset: Any, display_vars: List[str], title: str, figsize: tuple) -> bool: ...

def _display_xarray_dataset(dataset: Any, **kwargs: Any) -> Any: ...

_DISPLAY_HANDLERS: Any
def _display_array_data(data: Any, source_type: Any, **kwargs: Any) -> Any: ...

def register_display_handler(obj_type: str, handler_func: Callable[[Dict[str, Any]], None]) -> Any: ...

def list_converters() -> List[Dict[str, Any]]: ...

def _should_enhance_object(obj: Any) -> bool: ...

def _enhanced_show_method(original_obj: Any) -> Any: ...

class EnhancedJavaObject:
    def __init__(self: Any, java_obj: Any) -> Any: ...
    def __getattr__(self: Any, name: Any) -> Any: ...
    def __setattr__(self: Any, name: Any, value: Any) -> Any: ...
    def __dir__(self: Any) -> Any: ...
    def __repr__(self: Any) -> Any: ...
    def _enhanced_show(self: Any, *args: Any, **kwargs: Any) -> Any: ...
    def _enhanced_setVisible(self: Any, visible: Any, **kwargs: Any) -> Any: ...

def enhance_java_object(obj: Any) -> Any: ...

def auto_enhance_java_objects(enabled: bool) -> Any: ...
