"""
Type stubs for core.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional

logger: Any
_ij: Any
_jvm_started: Any
class FijiNotFoundError:
    pass

def _configure_jvm(max_heap: Optional[str], min_heap: Optional[str], jvm_args: Optional[List[str]]) -> None: ...

def initialize(fiji_path: Optional[str], interactive: bool, ensure_java: bool, mode: str, max_heap: Optional[str], min_heap: Optional[str], jvm_args: Optional[List[str]]) -> None: ...

def _find_fiji(interactive: bool) -> Optional[str]: ...

def _prompt_for_fiji_path() -> Optional[str]: ...

def _validate_fiji_path(fiji_path: str) -> bool: ...

def ij() -> Any: ...

def is_initialized() -> bool: ...

def setup_dynamic_imports(module_globals: Dict[str, Any], package_name: str, known_classes: Optional[List[str]], include_abstract: bool, include_interfaces: bool) -> Dict[str, Any]: ...

def to_python(obj: Any, **kwargs: Any) -> Any: ...

def from_java(obj: Any, **kwargs: Any) -> Any: ...

def show(obj: Any, **kwargs: Any) -> Any: ...
