"""
Type stubs for java_utils.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

logger: Any
REQUIRED_JAVA_VERSION: Any
MIN_JAVA_VERSION: Any
def check_java_installation() -> Dict[str, Any]: ...

def _find_java_executable() -> Optional[str]: ...

def _parse_java_version(version_output: str) -> Dict[str, Any]: ...

def ensure_java_available(required_version: int, auto_install: bool) -> bool: ...

def install_openjdk(version: int) -> bool: ...

def print_java_status() -> Any: ...

def setup_java_environment() -> bool: ...

def inspect(class_or_object: Union[str, Any], keyword: str, methods: bool, fields: bool, constructors: bool, static_only: bool, case_sensitive: bool, max_results: int) -> None: ...

def _resolve_java_object(class_or_object: Union[str, Any]) -> Optional[Any]: ...

def _get_class_name(java_object: Any) -> str: ...

def _get_full_class_name(java_object: Any) -> str: ...

def _get_package_name(java_object: Any) -> str: ...

def _show_constructors_from_jreflect(java_object: Any, keyword: str, case_sensitive: bool, max_results: int) -> Any: ...

def _show_methods_from_jreflect(java_object: Any, keyword: str, case_sensitive: bool, static_only: bool, max_results: int) -> Any: ...

def _show_fields_from_jreflect(java_object: Any, keyword: str, case_sensitive: bool, static_only: bool, max_results: int) -> Any: ...

def _matches_keyword(name: str, keyword: str, case_sensitive: bool) -> bool: ...

def get_methods(class_or_object: Union[str, Any], static_only: bool, include_inherited: bool) -> list: ...

def get_fields(class_or_object: Union[str, Any], static_only: bool) -> list: ...

def get_inner_classes(class_or_object: Union[str, Any]) -> list: ...

def is_instance_of(obj: Any, jtype: Union[str, Any]) -> bool: ...

def reflect_java_object(data: Any, aspect: str) -> List[Dict[str, Any]]: ...

def find_members(class_or_object: Union[str, Any], keyword: str, include_methods: bool, include_fields: bool, include_inner_classes: bool, static_only: bool, case_sensitive: bool) -> Dict[str, list]: ...

def discover_java_classes(package_name: str, known_classes: Optional[List[str]], include_abstract: bool, include_interfaces: bool) -> List[str]: ...

def _scan_package_from_jars(package_name: str, logger: Any) -> List[str]: ...

def _scan_pysnt_modules_for_classes(package_name: str) -> List[str]: ...

def _extract_class_lists_from_content(content: str) -> List[str]: ...
