"""
Type stubs for setup_utils.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable

def get_config_dir() -> Path: ...

def load_config() -> Dict[str, Any]: ...

def save_config(config: Dict[str, Any]) -> bool: ...

def set_fiji_path(fiji_path: str, validate: bool) -> bool: ...

def get_fiji_path() -> Optional[str]: ...

def clear_fiji_path(reset_env: bool) -> bool: ...

def reset_fiji_path() -> bool: ...

def get_config_info() -> Dict[str, Any]: ...

def is_fiji_valid() -> bool: ...

def get_fiji_status() -> Dict[str, Any]: ...

def show_config_status() -> Any: ...

def auto_detect_and_configure() -> Optional[str]: ...

def setup_fiji_environment(fiji_path: str, permanent: bool) -> bool: ...

def _setup_permanent_fiji_path(fiji_path: str) -> bool: ...

def find_fiji_installations() -> List[str]: ...

def check_fiji_installation(fiji_path: str) -> dict: ...

def print_fiji_status(fiji_path: str) -> Any: ...

def interactive_fiji_setup() -> Any: ...
