"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class AllenUtils:
    """
    sc.fiji.snt.annotation.AllenUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.139790
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def assignAnnotationsFromNodeValues(self, arg0: Tree) -> None: ...
    
    # Multiple overloads for assignHemisphereTags
    def assignHemisphereTags(self, arg0: Tree) -> None: ...
    # def assignHemisphereTags(self, arg0: DirectedWeightedGraph) -> None: ...
    
    def assignToLeftHemisphere(self, arg0: Tree) -> None: ...
    
    def assignToRightHemisphere(self, arg0: Tree) -> None: ...
    
    def brainCenter(self) -> SNTPoint: ...
    
    def getAnatomicalPlane(self, arg0: str) -> str: ...
    
    def getAxisDefiningSagittalPlane(self) -> int: ...
    
    def getCartesianPlane(self, arg0: str) -> str: ...
    
    # Multiple overloads for getCompartment
    def getCompartment(self, arg0: str) -> Any: ...
    # def getCompartment(self, arg0: int) -> Any: ...
    
    def getHemisphere(self, arg0: Tree) -> str: ...
    
    def getHighestOntologyDepth(self) -> int: ...
    
    # Multiple overloads for getOntologies
    def getOntologies(self) -> List[Any]: ...
    # def getOntologies(self, arg0: int, arg1: bool) -> List[Any]: ...
    
    def getRootMesh(self, arg0: Any) -> Any: ...
    
    def getTreeModel(self, arg0: bool) -> Any: ...
    
    def getXYZLabels(self) -> Any: ...
    
    # Multiple overloads for isLeftHemisphere
    def isLeftHemisphere(self, arg0: float, arg1: float, arg2: float) -> bool: ...
    # def isLeftHemisphere(self, arg0: SNTPoint) -> bool: ...
    # def isLeftHemisphere(self, arg0: Tree) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def splitByHemisphere(self, arg0: DirectedWeightedGraph) -> List[Any]: ...
    
    def transferAnnotationIdsToNodeValues(self, arg0: Tree) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class AllenCompartment:
    """
    sc.fiji.snt.annotation.AllenCompartment
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.134408
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def acronym(self) -> str: ...
    
    def aliases(self) -> Any: ...
    
    def color(self) -> Any: ...
    
    # Multiple overloads for getAncestor
    def getAncestor(self, arg0: int) -> Any: ...
    # def getAncestor(self, arg0: int) -> Any: ...
    
    def getAncestors(self) -> List[Any]: ...
    
    # Multiple overloads for getChildren
    def getChildren(self, arg0: int) -> List[Any]: ...
    # def getChildren(self) -> List[Any]: ...
    
    def getMesh(self) -> Any: ...
    
    def getOntologyDepth(self) -> int: ...
    
    # Multiple overloads for getParent
    def getParent(self) -> Any: ...
    # def getParent(self) -> Any: ...
    
    def getTreePath(self) -> List[Any]: ...
    
    def getUUID(self) -> Any: ...
    
    def id(self) -> int: ...
    
    def includes(self, arg0: Any) -> bool: ...
    
    def isChildOf(self, arg0: Any) -> bool: ...
    
    def isMeshAvailable(self) -> bool: ...
    
    def isParentOf(self, arg0: Any) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def name(self) -> str: ...
    
    def __getattr__(self, name: str) -> Any: ...


class InsectBrainCompartment:
    """
    sc.fiji.snt.annotation.InsectBrainCompartment
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.246902
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def acronym(self) -> str: ...
    
    def aliases(self) -> Any: ...
    
    def color(self) -> Any: ...
    
    def getAncestor(self, arg0: int) -> Any: ...
    
    def getMesh(self) -> Any: ...
    
    def getOntologyDepth(self) -> int: ...
    
    def getParent(self) -> Any: ...
    
    def id(self) -> int: ...
    
    def isChildOf(self, arg0: Any) -> bool: ...
    
    def isMeshAvailable(self) -> bool: ...
    
    def isParentOf(self, arg0: Any) -> bool: ...
    
    def name(self) -> str: ...
    
    def __getattr__(self, name: str) -> Any: ...


class InsectBrainUtils:
    """
    sc.fiji.snt.annotation.InsectBrainUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.252184
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getAllNeuronIDs(self) -> List[Any]: ...
    
    def getAllSpecies(self) -> List[Any]: ...
    
    def getBrainCompartments(self, arg0: int, arg1: str) -> List[Any]: ...
    
    def getBrainJSON(self, arg0: int) -> Any: ...
    
    def getBrainMeshes(self, arg0: int, arg1: str) -> List[Any]: ...
    
    def getSpeciesNeuronIDs(self, arg0: int) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class VFBUtils:
    """
    sc.fiji.snt.annotation.VFBUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.762150
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def brainBarycentre(self, arg0: str) -> SNTPoint: ...
    
    # Multiple overloads for getMesh
    def getMesh(self, arg0: str, arg1: Any) -> Any: ...
    # def getMesh(self, arg0: str) -> Any: ...
    
    def getRefBrain(self, arg0: str) -> Any: ...
    
    def getXYZLabels(self) -> Any: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def main(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ZBAtlasUtils:
    """
    sc.fiji.snt.annotation.ZBAtlasUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.796060
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def brainBarycentre(self) -> SNTPoint: ...
    
    def getRefBrain(self) -> Any: ...
    
    def getXYZLabels(self) -> Any: ...
    
    def isDatabaseAvailable(self) -> bool: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...