"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class BiSearch:
    """
    sc.fiji.snt.tracing.BiSearch
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.223748
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addProgressListener(self, arg0: Any) -> None: ...
    
    def getNodesAsImage(self) -> Any: ...
    
    def getResult(self) -> Any: ...
    
    def pointsConsideredInSearch(self) -> int: ...
    
    def printStatus(self) -> None: ...
    
    def reportFinished(self, arg0: bool) -> None: ...
    
    def run(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class BiSearchNode:
    """
    sc.fiji.snt.tracing.BiSearchNode
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.231773
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getF(self, arg0: bool) -> float: ...
    
    def getFFromGoal(self) -> float: ...
    
    def getFFromStart(self) -> float: ...
    
    def getG(self, arg0: bool) -> float: ...
    
    def getGFromGoal(self) -> float: ...
    
    def getGFromStart(self) -> float: ...
    
    def getHeapHandle(self, arg0: bool) -> Any: ...
    
    def getHeapHandleFromGoal(self) -> Any: ...
    
    def getHeapHandleFromStart(self) -> Any: ...
    
    def getPredecessorFromGoal(self) -> Any: ...
    
    def getPredecessorFromStart(self) -> Any: ...
    
    def getState(self, arg0: bool) -> Any: ...
    
    def getStateFromGoal(self) -> Any: ...
    
    def getStateFromStart(self) -> Any: ...
    
    def getX(self) -> int: ...
    
    def getY(self) -> int: ...
    
    def getZ(self) -> int: ...
    
    def heapDecreaseKey(self, arg0: bool) -> None: ...
    
    def heapInsert(self, arg0: Any, arg1: bool) -> None: ...
    
    def setFFromGoal(self, arg0: float) -> None: ...
    
    def setFFromStart(self, arg0: float) -> None: ...
    
    def setFrom(self, arg0: float, arg1: float, arg2: Any, arg3: bool) -> None: ...
    
    def setFromGoal(self, arg0: float, arg1: float, arg2: Any) -> None: ...
    
    def setFromStart(self, arg0: float, arg1: float, arg2: Any) -> None: ...
    
    def setGFromGoal(self, arg0: float) -> None: ...
    
    def setGFromStart(self, arg0: float) -> None: ...
    
    def setHeapHandle(self, arg0: Any, arg1: bool) -> None: ...
    
    def setHeapHandleFromGoal(self, arg0: Any) -> None: ...
    
    def setHeapHandleFromStart(self, arg0: Any) -> None: ...
    
    def setPosition(self, arg0: int, arg1: int, arg2: int) -> None: ...
    
    def setPredecessorFromGoal(self, arg0: Any) -> None: ...
    
    def setPredecessorFromStart(self, arg0: Any) -> None: ...
    
    def setState(self, arg0: Any, arg1: bool) -> None: ...
    
    def setStateFromGoal(self, arg0: Any) -> None: ...
    
    def setStateFromStart(self, arg0: Any) -> None: ...
    
    def setX(self, arg0: int) -> None: ...
    
    def setY(self, arg0: int) -> None: ...
    
    def setZ(self, arg0: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class DefaultSearchNode:
    """
    sc.fiji.snt.tracing.DefaultSearchNode
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.254257
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def asPath(self, arg0: float, arg1: float, arg2: float, arg3: str) -> Any: ...
    
    def asPathReversed(self, arg0: float, arg1: float, arg2: float, arg3: str) -> Any: ...
    
    # Multiple overloads for compareTo
    def compareTo(self, arg0: Any) -> int: ...
    # def compareTo(self, arg0: Any) -> int: ...
    
    def getHandle(self) -> Any: ...
    
    def getPredecessor(self) -> Any: ...
    
    def getX(self) -> int: ...
    
    def getY(self) -> int: ...
    
    def getZ(self) -> int: ...
    
    def setFrom(self, arg0: Any) -> None: ...
    
    def setHandle(self, arg0: Any) -> None: ...
    
    def setPredecessor(self, arg0: Any) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class FillerThread:
    """
    sc.fiji.snt.tracing.FillerThread
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.271514
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addNode(self, arg0: Any, arg1: bool) -> None: ...
    
    def addProgressListener(self, arg0: Any) -> None: ...
    
    def createNewNode(self, arg0: int, arg1: int, arg2: int, arg3: float, arg4: float, arg5: Any, arg6: int) -> Any: ...
    
    # Multiple overloads for fromFill
    def fromFill(self, arg0: Any, arg1: Any, arg2: Any, arg3: Any) -> Any: ...
    # def fromFill(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    
    def getDistanceAtPoint(self, arg0: float, arg1: float, arg2: float) -> float: ...
    
    def getExitReason(self) -> int: ...
    
    def getFill(self) -> Any: ...
    
    def getNodesAsImage(self) -> Any: ...
    
    def getNodesAsImageFromGoal(self) -> Any: ...
    
    def getNodesAsImageFromStart(self) -> Any: ...
    
    def getResult(self) -> Any: ...
    
    def getThreshold(self) -> float: ...
    
    def pointsConsideredInSearch(self) -> int: ...
    
    def printStatus(self) -> None: ...
    
    def reportFinished(self, arg0: bool) -> None: ...
    
    def run(self) -> None: ...
    
    def setSourcePaths(self, arg0: List[Any]) -> None: ...
    
    def setStopAtThreshold(self, arg0: bool) -> None: ...
    
    def setStoreExtraNodes(self, arg0: bool) -> None: ...
    
    def setThreshold(self, arg0: float) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PathResult:
    """
    sc.fiji.snt.tracing.PathResult
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.458970
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getErrorMessage(self) -> str: ...
    
    def getNumberOfPoints(self) -> int: ...
    
    def getPath(self) -> Any: ...
    
    def getSuccess(self) -> bool: ...
    
    def setErrorMessage(self, arg0: str) -> None: ...
    
    def setPath(self, arg0: Any) -> None: ...
    
    def setSuccess(self, arg0: bool) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SearchNode:
    """
    sc.fiji.snt.tracing.SearchNode
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.739613
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def getX(self) -> int: ...
    
    def getY(self) -> int: ...
    
    def getZ(self) -> int: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SearchThread:
    """
    sc.fiji.snt.tracing.SearchThread
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.743349
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addNode(self, arg0: Any, arg1: bool) -> None: ...
    
    def addProgressListener(self, arg0: Any) -> None: ...
    
    def createNewNode(self, arg0: int, arg1: int, arg2: int, arg3: float, arg4: float, arg5: Any, arg6: int) -> Any: ...
    
    def getExitReason(self) -> int: ...
    
    def getNodesAsImageFromGoal(self) -> Any: ...
    
    def getNodesAsImageFromStart(self) -> Any: ...
    
    def getResult(self) -> Any: ...
    
    def pointsConsideredInSearch(self) -> int: ...
    
    def printStatus(self) -> None: ...
    
    def reportFinished(self, arg0: bool) -> None: ...
    
    def run(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class TracerThread:
    """
    sc.fiji.snt.tracing.TracerThread
    
    Generated from cached signatures.
    Extracted: 2025-11-02T09:55:54.785846
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def addNode(self, arg0: Any, arg1: bool) -> None: ...
    
    def addProgressListener(self, arg0: Any) -> None: ...
    
    def createNewNode(self, arg0: int, arg1: int, arg2: int, arg3: float, arg4: float, arg5: Any, arg6: int) -> Any: ...
    
    def getExitReason(self) -> int: ...
    
    def getNodesAsImageFromGoal(self) -> Any: ...
    
    def getNodesAsImageFromStart(self) -> Any: ...
    
    def getResult(self) -> Any: ...
    
    def pointsConsideredInSearch(self) -> int: ...
    
    def printStatus(self) -> None: ...
    
    def reportFinished(self, arg0: bool) -> None: ...
    
    def run(self) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def artist(*args: Any, **kwargs: Any) -> Any: ...
def cost(*args: Any, **kwargs: Any) -> Any: ...
def heuristic(*args: Any, **kwargs: Any) -> Any: ...
def image(*args: Any, **kwargs: Any) -> Any: ...
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...