"""
Type stubs for enhancement.py

Auto-generated stub file.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Tuple

def _should_enhance_object(obj: Any) -> bool: ...

def _is_gui_object(obj: Any) -> bool: ...

class EnhancedJavaObject:
    def __init__(self: Any, java_obj: Any) -> Any: ...
    def __getattr__(self: Any, name: Any) -> Any: ...
    def __setattr__(self: Any, name: Any, value: Any) -> Any: ...
    def __dir__(self: Any) -> Any: ...
    def __repr__(self: Any) -> Any: ...
    def _enhanced_show(self: Any, *args: Any, **kwargs: Any) -> Any: ...
    def _enhanced_setVisible(self: Any, visible: Any, **kwargs: Any) -> Any: ...

def _enhanced_show_method(original_obj: Any) -> Any: ...

def enhance_java_object(obj: Any) -> Any: ...

def auto_enhance_java_objects(enabled: bool) -> Any: ...

def _is_snt_tree(obj: Any) -> bool: ...

def _is_snt_path(obj: Any) -> bool: ...

def _is_xarray_object(obj: Any) -> bool: ...
