"""Comprehensive type stubs for Java classes."""

from typing import Any, List, Dict, Optional, Union, overload, Set, Callable, Tuple

class BoundingBox:
    """
    sc.fiji.snt.util.BoundingBox
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.184987
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def append(self, arg0: Any) -> None: ...
    
    # Multiple overloads for clone
    def clone(self) -> Any: ...
    # def clone(self) -> BoundingBox: ...
    
    def combine(self, arg0: BoundingBox) -> None: ...
    
    def compute(self, arg0: Any) -> None: ...
    
    # Multiple overloads for contains
    def contains(self, arg0: SNTPoint) -> bool: ...
    # def contains(self, arg0: BoundingBox) -> bool: ...
    
    def contains2D(self, arg0: SNTPoint) -> bool: ...
    
    def depth(self) -> float: ...
    
    def getCalibration(self) -> Any: ...
    
    def getCentroid(self) -> SNTPoint: ...
    
    def getDiagonal(self) -> float: ...
    
    # Multiple overloads for getDimensions
    def getDimensions(self) -> Any: ...
    # def getDimensions(self, arg0: bool) -> Any: ...
    
    def getUnit(self) -> str: ...
    
    def hasDimensions(self) -> bool: ...
    
    def height(self) -> float: ...
    
    def inferSpacing(self, arg0: List[Any]) -> None: ...
    
    def intersection(self, arg0: BoundingBox) -> BoundingBox: ...
    
    def isScaled(self) -> bool: ...
    
    def origin(self) -> PointInImage: ...
    
    def originOpposite(self) -> PointInImage: ...
    
    def scale(self, arg0: Any) -> BoundingBox: ...
    
    def setDimensions(self, arg0: int, arg1: int, arg2: int) -> None: ...
    
    def setOrigin(self, arg0: PointInImage) -> None: ...
    
    def setOriginOpposite(self, arg0: PointInImage) -> None: ...
    
    def setSpacing(self, arg0: float, arg1: float, arg2: float, arg3: str) -> None: ...
    
    def setUnit(self, arg0: str) -> None: ...
    
    def shift(self, arg0: Any) -> BoundingBox: ...
    
    def toBoundingBox3d(self) -> Any: ...
    
    def unscaledOrigin(self) -> PointInImage: ...
    
    def unscaledOriginOpposite(self) -> PointInImage: ...
    
    def width(self) -> float: ...
    
    # Fields
    info: str
    xSpacing: float
    ySpacing: float
    zSpacing: float
    
    def __getattr__(self, name: str) -> Any: ...


class ColorMaps:
    """
    sc.fiji.snt.util.ColorMaps
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.188124
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    # Multiple overloads for applyPlasma
    def applyPlasma(self, arg0: Any, arg1: int, arg2: bool) -> None: ...
    # def applyPlasma(self, arg0: Any) -> None: ...
    
    # Multiple overloads for applyViridis
    def applyViridis(self, arg0: Any, arg1: int, arg2: bool) -> None: ...
    # def applyViridis(self, arg0: Any) -> None: ...
    
    def discreteColors(self, arg0: Any, arg1: int) -> Any: ...
    
    def discreteColorsAWT(self, arg0: Any, arg1: int) -> Any: ...
    
    def get(self, arg0: str) -> Any: ...
    
    def glasbeyColorsAWT(self, arg0: int) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class CrossoverFinder:
    """
    sc.fiji.snt.util.CrossoverFinder
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.201829
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def find(self, arg0: List[Any], arg1: Any) -> List[Any]: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ImgUtils:
    """
    sc.fiji.snt.util.ImgUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.235694
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def createIntervals(self, arg0: Any, arg1: Any) -> List[Any]: ...
    
    # Multiple overloads for crop
    def crop(self, arg0: Any, arg1: Any, arg2: Any, arg3: int, arg4: bool) -> Any: ...
    # def crop(self, arg0: Any, arg1: Any, arg2: Any, arg3: bool) -> Any: ...
    # def crop(self, arg0: Any, arg1: Any, arg2: Any, arg3: int) -> Any: ...
    # def crop(self, arg0: Any, arg1: Any, arg2: Any, arg3: int, arg4: bool, arg5: bool) -> Any: ...
    
    def dropSingletonDimensions(self, arg0: Any) -> Any: ...
    
    def findSpatialAxisIndices(self, arg0: Any) -> Any: ...
    
    def findSpatialAxisIndicesWithFallback(self, arg0: Any) -> Any: ...
    
    def getCalibration(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for getCtSlice
    def getCtSlice(self, arg0: Any) -> Any: ...
    # def getCtSlice(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    # def getCtSlice(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    # def getCtSlice(self, arg0: Any) -> Any: ...
    
    # Multiple overloads for getCtSlice3d
    def getCtSlice3d(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    # def getCtSlice3d(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    
    def getOrigin(self, arg0: Any, arg1: Any) -> float: ...
    
    def getOrigins(self, arg0: Any) -> Any: ...
    
    def imgPlusToCalibration(self, arg0: Any) -> Any: ...
    
    def impToRealRai5d(self, arg0: Any) -> Any: ...
    
    def maxDimension(self, arg0: Any) -> int: ...
    
    def outOfBounds(self, arg0: Any, arg1: Any, arg2: Any) -> bool: ...
    
    def raiToImp(self, arg0: Any, arg1: str) -> Any: ...
    
    def splitIntoBlocks(self, arg0: Any, arg1: Any) -> List[Any]: ...
    
    def subInterval(self, arg0: Any, arg1: Any, arg2: Any, arg3: int) -> Any: ...
    
    def subVolume(self, arg0: Any, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int) -> Any: ...
    
    # Multiple overloads for toImagePlus
    def toImagePlus(self, arg0: Any, arg1: Any, arg2: Any) -> Any: ...
    # def toImagePlus(self, arg0: Any) -> Any: ...
    # def toImagePlus(self, arg0: Any, arg1: Any, arg2: Any, arg3: int, arg4: bool) -> Any: ...
    # def toImagePlus(self, arg0: Any, arg1: str) -> Any: ...
    
    def wrapWithAxes(self, arg0: Any, arg1: Any, arg2: str) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class ImpUtils:
    """
    sc.fiji.snt.util.ImpUtils
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.243295
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def applyColorTable(self, arg0: Any, arg1: Any) -> None: ...
    
    def ascii(self, arg0: Any, arg1: bool, arg2: int, arg3: int) -> str: ...
    
    def binarize(self, arg0: Any, arg1: float, arg2: float) -> None: ...
    
    def calibrationToAxes(self, arg0: Any, arg1: int) -> Any: ...
    
    # Multiple overloads for combineSkeletons
    def combineSkeletons(self, arg0: List[Any]) -> Any: ...
    # def combineSkeletons(self, arg0: List[Any], arg1: bool) -> Any: ...
    
    def convertRGBtoComposite(self, arg0: Any) -> Any: ...
    
    def convertTo32bit(self, arg0: Any) -> None: ...
    
    def convertTo8bit(self, arg0: Any) -> None: ...
    
    def convertToSimple2D(self, arg0: Any, arg1: int) -> Any: ...
    
    def create(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: int) -> Any: ...
    
    def crop(self, arg0: Any, arg1: Union[int, float]) -> None: ...
    
    def demo(self, arg0: str) -> Any: ...
    
    def getCT(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    
    def getChannel(self, arg0: Any, arg1: int) -> Any: ...
    
    def getCurrentImage(self) -> Any: ...
    
    def getForegroundRect(self, arg0: Any, arg1: Union[int, float]) -> Any: ...
    
    def getFrame(self, arg0: Any, arg1: int) -> Any: ...
    
    # Multiple overloads for getMIP
    def getMIP(self, arg0: Any) -> Any: ...
    # def getMIP(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    # def getMIP(self, arg0: List[Any]) -> Any: ...
    
    def getMinMax(self, arg0: Any) -> Any: ...
    
    def getSliceLabels(self, arg0: Any) -> List[Any]: ...
    
    def getSystemClipboard(self, arg0: bool) -> Any: ...
    
    def imageTypeToString(self, arg0: int) -> str: ...
    
    def invertLut(self, arg0: Any) -> None: ...
    
    def isBinary(self, arg0: Any) -> bool: ...
    
    def isPointVisible(self, arg0: Any, arg1: int, arg2: int) -> bool: ...
    
    def isVirtualStack(self, arg0: Any) -> bool: ...
    
    def nextZoomLevel(self, arg0: float) -> float: ...
    
    # Multiple overloads for open
    def open(self, arg0: str, arg1: str) -> Any: ...
    # def open(self, arg0: str) -> Any: ...
    # def open(self, arg0: str) -> Any: ...
    # def open(self, arg0: str, arg1: str) -> Any: ...
    
    def previousZoomLevel(self, arg0: float) -> float: ...
    
    def removeIsolatedPixels(self, arg0: Any) -> None: ...
    
    def removeSlices(self, arg0: Any, arg1: List[Any]) -> None: ...
    
    def rotate90(self, arg0: Any, arg1: str) -> None: ...
    
    def sameCTDimensions(self, arg0: Any, arg1: Any) -> bool: ...
    
    def sameCalibration(self, arg0: Any, arg1: Any) -> bool: ...
    
    def sameXYZDimensions(self, arg0: Any, arg1: Any) -> bool: ...
    
    def save(self, arg0: Any, arg1: str) -> None: ...
    
    def setLut(self, arg0: Any, arg1: str) -> None: ...
    
    def toDataset(self, arg0: Any) -> Any: ...
    
    def toImgPlus(self, arg0: Any) -> Any: ...
    
    def toImgPlus3D(self, arg0: Any, arg1: int, arg2: int) -> Any: ...
    
    def toStack(self, arg0: List[Any]) -> Any: ...
    
    # Multiple overloads for zoomTo
    def zoomTo(self, arg0: Any, arg1: List[Any]) -> float: ...
    # def zoomTo(self, arg0: Any, arg1: float, arg2: int, arg3: int) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class PointInImage:
    """
    sc.fiji.snt.util.PointInImage
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.481972
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def chebyshevDxTo(self, arg0: PointInImage) -> float: ...
    
    def chebyshevXYdxTo(self, arg0: PointInImage) -> float: ...
    
    def chebyshevZdxTo(self, arg0: PointInImage) -> float: ...
    
    # Multiple overloads for clone
    def clone(self) -> PointInImage: ...
    # def clone(self) -> Any: ...
    
    # Multiple overloads for distanceSquaredTo
    def distanceSquaredTo(self, arg0: PointInImage) -> float: ...
    # def distanceSquaredTo(self, arg0: float, arg1: float, arg2: float) -> float: ...
    
    def distanceTo(self, arg0: PointInImage) -> float: ...
    
    def euclideanDxTo(self, arg0: PointInImage) -> float: ...
    
    def getAnnotation(self) -> Any: ...
    
    def getCoordinateOnAxis(self, arg0: int) -> float: ...
    
    def getHemisphere(self) -> str: ...
    
    def getPath(self) -> Path: ...
    
    # Multiple overloads for getUnscaledPoint
    def getUnscaledPoint(self, arg0: int) -> Any: ...
    # def getUnscaledPoint(self) -> Any: ...
    
    def getX(self) -> float: ...
    
    def getY(self) -> float: ...
    
    def getZ(self) -> float: ...
    
    def isReal(self) -> bool: ...
    
    def isSameLocation(self, arg0: PointInImage) -> bool: ...
    
    def scale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    
    def setAnnotation(self, arg0: Any) -> None: ...
    
    def setHemisphere(self, arg0: str) -> None: ...
    
    def setPath(self, arg0: Path) -> None: ...
    
    def transform(self, arg0: Any) -> PointInImage: ...
    
    # Fields
    onPath: Path
    radius: float
    v: float
    x: float
    y: float
    z: float
    
    def __getattr__(self, name: str) -> Any: ...


class SNTColor:
    """
    sc.fiji.snt.util.SNTColor
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.565573
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def alphaColor(self, arg0: Any, arg1: float) -> Any: ...
    
    def average(self, arg0: List[Any]) -> Any: ...
    
    def color(self) -> Any: ...
    
    def colorToString(self, arg0: Any) -> str: ...
    
    def contrastColor(self, arg0: Any) -> Any: ...
    
    def fromHex(self, arg0: str) -> Any: ...
    
    # Multiple overloads for getDistinctColors
    def getDistinctColors(self, arg0: int) -> Any: ...
    # def getDistinctColors(self, arg0: int, arg1: str) -> Any: ...
    
    def getDistinctColorsAWT(self, arg0: int) -> Any: ...
    
    # Multiple overloads for getDistinctColorsHex
    def getDistinctColorsHex(self, arg0: int, arg1: str) -> Any: ...
    # def getDistinctColorsHex(self, arg0: int) -> Any: ...
    
    def interpolateNullEntries(self, arg0: Any) -> None: ...
    
    def isTypeDefined(self) -> bool: ...
    
    def setAWTColor(self, arg0: Any) -> None: ...
    
    def setSWCType(self, arg0: int) -> None: ...
    
    def type(self) -> int: ...
    
    def valueOf(self, arg0: str) -> Any: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SNTPoint:
    """
    sc.fiji.snt.util.SNTPoint
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.568084
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def average(self, arg0: List[Any]) -> PointInImage: ...
    
    def getAnnotation(self) -> Any: ...
    
    def getCoordinateOnAxis(self, arg0: int) -> float: ...
    
    def getHemisphere(self) -> str: ...
    
    def getX(self) -> float: ...
    
    def getY(self) -> float: ...
    
    def getZ(self) -> float: ...
    
    # Multiple overloads for of
    def of(self, arg0: Union[int, float], arg1: Union[int, float], arg2: Union[int, float]) -> PointInImage: ...
    # def of(self, arg0: Any) -> PointInImage: ...
    
    def setAnnotation(self, arg0: Any) -> None: ...
    
    def setHemisphere(self, arg0: str) -> None: ...
    
    def __getattr__(self, name: str) -> Any: ...


class SWCPoint:
    """
    sc.fiji.snt.util.SWCPoint
    
    Generated from cached signatures.
    Extracted: 2026-01-02T22:23:57.644347
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    
    def chebyshevDxTo(self, arg0: PointInImage) -> float: ...
    
    def chebyshevXYdxTo(self, arg0: PointInImage) -> float: ...
    
    def chebyshevZdxTo(self, arg0: PointInImage) -> float: ...
    
    # Multiple overloads for clone
    def clone(self) -> PointInImage: ...
    # def clone(self) -> Any: ...
    
    def collectionAsReader(self, arg0: List[Any]) -> Any: ...
    
    # Multiple overloads for compareTo
    def compareTo(self, arg0: SWCPoint) -> int: ...
    # def compareTo(self, arg0: Any) -> int: ...
    
    # Multiple overloads for distanceSquaredTo
    def distanceSquaredTo(self, arg0: PointInImage) -> float: ...
    # def distanceSquaredTo(self, arg0: float, arg1: float, arg2: float) -> float: ...
    
    def distanceTo(self, arg0: PointInImage) -> float: ...
    
    def euclideanDxTo(self, arg0: PointInImage) -> float: ...
    
    def flush(self, arg0: List[Any], arg1: Any) -> None: ...
    
    def getAnnotation(self) -> Any: ...
    
    def getColor(self) -> Any: ...
    
    def getCoordinateOnAxis(self, arg0: int) -> float: ...
    
    def getHemisphere(self) -> str: ...
    
    def getNextPoints(self) -> List[Any]: ...
    
    def getPath(self) -> Path: ...
    
    def getTags(self) -> str: ...
    
    # Multiple overloads for getUnscaledPoint
    def getUnscaledPoint(self, arg0: int) -> Any: ...
    # def getUnscaledPoint(self) -> Any: ...
    
    def getX(self) -> float: ...
    
    def getY(self) -> float: ...
    
    def getZ(self) -> float: ...
    
    def isReal(self) -> bool: ...
    
    def isSameLocation(self, arg0: PointInImage) -> bool: ...
    
    def previous(self) -> SWCPoint: ...
    
    def scale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    
    def setAnnotation(self, arg0: Any) -> None: ...
    
    def setColor(self, arg0: Any) -> None: ...
    
    def setHemisphere(self, arg0: str) -> None: ...
    
    def setPath(self, arg0: Path) -> None: ...
    
    def setPrevious(self, arg0: SWCPoint) -> None: ...
    
    def setTags(self, arg0: str) -> None: ...
    
    def transform(self, arg0: Any) -> PointInImage: ...
    
    def xSeparationFromPreviousPoint(self) -> float: ...
    
    def ySeparationFromPreviousPoint(self) -> float: ...
    
    def zSeparationFromPreviousPoint(self) -> float: ...
    
    # Fields
    id: int
    onPath: Path
    parent: int
    radius: float
    type: int
    v: float
    x: float
    y: float
    z: float
    
    def __getattr__(self, name: str) -> Any: ...



# Imported functions
def setup_module_classes(*args: Any, **kwargs: Any) -> Any: ...

# Imported classes
class Any: ...
class Dict: ...
class List: ...